# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plugins/jgames/jgameswidget.ui'
#
# Created: Mon Apr 19 15:20:29 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_groupchatwidget(object):
    def setupUi(self, groupchatwidget):
        groupchatwidget.setObjectName("groupchatwidget")
        groupchatwidget.resize(592, 725)
        groupchatwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout_2 = QtGui.QGridLayout(groupchatwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtGui.QSplitter(groupchatwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.gameWidget = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameWidget.sizePolicy().hasHeightForWidth())
        self.gameWidget.setSizePolicy(sizePolicy)
        self.gameWidget.setObjectName("gameWidget")
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.disco_info = QtGui.QLabel(self.widget)
        self.disco_info.setText("")
        self.disco_info.setObjectName("disco_info")
        self.gridLayout.addWidget(self.disco_info, 0, 0, 1, 1)
        self.info = QtGui.QTextBrowser(self.widget)
        self.info.setMinimumSize(QtCore.QSize(0, 1))
        self.info.setOpenExternalLinks(True)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 1, 0, 1, 1)
        self.users = QtGui.QTreeWidget(self.widget)
        self.users.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.users.setIconSize(QtCore.QSize(32, 32))
        self.users.setIndentation(0)
        self.users.setRootIsDecorated(False)
        self.users.setObjectName("users")
        self.gridLayout.addWidget(self.users, 2, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.viewWidget = QtGui.QWidget(self.widget)
        self.viewWidget.setObjectName("viewWidget")
        self.verticalLayout.addWidget(self.viewWidget)
        self.editLayout = QtGui.QVBoxLayout()
        self.editLayout.setSpacing(6)
        self.editLayout.setMargin(0)
        self.editLayout.setObjectName("editLayout")
        self.lineWidget = QtGui.QWidget(self.widget)
        self.lineWidget.setMinimumSize(QtCore.QSize(0, 10))
        self.lineWidget.setObjectName("lineWidget")
        self.editLayout.addWidget(self.lineWidget)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.linkButton = QtGui.QToolButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/16x16/actions/anchor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkButton.setIcon(icon)
        self.linkButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.linkButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.linkButton.setObjectName("linkButton")
        self.hboxlayout.addWidget(self.linkButton)
        self.boldButton = QtGui.QToolButton(self.widget)
        self.boldButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldButton.setIcon(icon1)
        self.boldButton.setCheckable(True)
        self.boldButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.boldButton.setObjectName("boldButton")
        self.hboxlayout.addWidget(self.boldButton)
        self.italicButton = QtGui.QToolButton(self.widget)
        self.italicButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicButton.setIcon(icon2)
        self.italicButton.setCheckable(True)
        self.italicButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.italicButton.setObjectName("italicButton")
        self.hboxlayout.addWidget(self.italicButton)
        self.underlineButton = QtGui.QToolButton(self.widget)
        self.underlineButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineButton.setIcon(icon3)
        self.underlineButton.setCheckable(True)
        self.underlineButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.underlineButton.setObjectName("underlineButton")
        self.hboxlayout.addWidget(self.underlineButton)
        self.colorButton = QtGui.QToolButton(self.widget)
        self.colorButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.colorButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.colorButton.setObjectName("colorButton")
        self.hboxlayout.addWidget(self.colorButton)
        self.backgroundButton = QtGui.QToolButton(self.widget)
        self.backgroundButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.backgroundButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.backgroundButton.setObjectName("backgroundButton")
        self.hboxlayout.addWidget(self.backgroundButton)
        self.fontSize = QtGui.QComboBox(self.widget)
        self.fontSize.setObjectName("fontSize")
        self.hboxlayout.addWidget(self.fontSize)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.smileys = QtGui.QToolButton(self.widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/16x16/emotes/biggrin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smileys.setIcon(icon4)
        self.smileys.setCheckable(True)
        self.smileys.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.smileys.setObjectName("smileys")
        self.hboxlayout.addWidget(self.smileys)
        self.sendButton = QtGui.QToolButton(self.widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/16x16/actions/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon5)
        self.sendButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout.addWidget(self.sendButton)
        self.editLayout.addLayout(self.hboxlayout)
        self.verticalLayout.addLayout(self.editLayout)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.pluginWidget = QtGui.QWidget(self.widget)
        self.pluginWidget.setObjectName("pluginWidget")
        self.gridLayout.addWidget(self.pluginWidget, 4, 0, 1, 1)
        self.selfAvatar = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selfAvatar.sizePolicy().hasHeightForWidth())
        self.selfAvatar.setSizePolicy(sizePolicy)
        self.selfAvatar.setText("")
        self.selfAvatar.setObjectName("selfAvatar")
        self.gridLayout.addWidget(self.selfAvatar, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(groupchatwidget)
        QtCore.QMetaObject.connectSlotsByName(groupchatwidget)

    def retranslateUi(self, groupchatwidget):
        groupchatwidget.setWindowTitle(QtGui.QApplication.translate("groupchatwidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Every multi-user chat can have topic of its discussion", None, QtGui.QApplication.UnicodeUTF8))
        self.users.headerItem().setText(0, QtGui.QApplication.translate("groupchatwidget", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.users.headerItem().setText(1, QtGui.QApplication.translate("groupchatwidget", "jid", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setText(QtGui.QApplication.translate("groupchatwidget", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setText(QtGui.QApplication.translate("groupchatwidget", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setText(QtGui.QApplication.translate("groupchatwidget", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.smileys.setToolTip(QtGui.QApplication.translate("groupchatwidget", "You can add emoticons by clicking here", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("groupchatwidget", "&Send", None, QtGui.QApplication.UnicodeUTF8))

