":)" = "smile.png"
":-)" = "smile.png"
";)" = "wink.png"
";-)" = "wink.png"
":D" = "biggrin.png"
":-D" = "biggrin.png"
":d" = "biggrin.png"
":-d" = "biggrin.png"
":P" = "tongue.png"
":p" = "tongue.png"
":-P" = "tongue.png"
":-p" = "tongue.png"
":o" = "impressed.png"
":O" = "impressed.png"
":-O" = "impressed.png"
":-o" = "impressed.png"
":-|" = "neutral.png"
":|" = "neutral.png"
":(" = "sad.png"
":-(" = "sad.png"
":X" = "silenced.png"
":x" = "silenced.png"
":-x" = "silenced.png"
":-X" = "silenced.png"
"8-" = "cool.png"
"%)" = "confused.png"
"%-)" = "confused.png"
"@@" = "confused.png"
":[" = "ashamed.png"
":-[" = "ashamed.png"
"oO" = "eh.png"
"*angel*" = "angel.png"
"*kidding*" = "kidding.png"
"*mad*" = "mad.png"
"*twisted*" = "twisted.png"
"*applause*" = "applause.png"
"*fear*" = "fear.png"
"*no*" = "naughty.png"
"*rolleyes*" = "rolleyes.png"
"*sick*" = "sick.png"
"*think*" = "think.png"
"*whistle*" = "whistle.png"