":)" = "smile.gif"
":-)" = "smile.gif"
";)" = "wink.gif"
";-)" = "wink.gif"
":D" = "biggrin.gif"
":-D" = "biggrin.gif"
":d" = "biggrin.gif"
":-d" = "biggrin.gif"
":P" = "tongue.gif"
":p" = "tongue.gif"
":-P" = "tongue.gif"
":-p" = "tongue.gif"
":o" = "impressed.gif"
":O" = "impressed.gif"
":-O" = "impressed.gif"
":-o" = "impressed.gif"
":-|" = "neutral.gif"
":|" = "neutral.gif"
":(" = "sad.gif"
":-(" = "sad.gif"
":X" = "silenced.gif"
":x" = "silenced.gif"
":-x" = "silenced.gif"
":-X" = "silenced.gif"
"8-" = "cool.gif"
"%)" = "confused.gif"
"%-)" = "confused.gif"
"@@" = "confused.gif"
":[" = "ashamed.gif"
":-[" = "ashamed.gif"
"oO" = "eh.gif"
"*angel*" = "angel.gif"
"*kidding*" = "kidding.gif"
"*mad*" = "mad.gif"
"*twisted*" = "twisted.gif"
"*applause*" = "applause.gif"
"*fear*" = "fear.gif"
"*no*" = "naughty.gif"
"*rolleyes*" = "rolleyes.gif"
"*sick*" = "sick.gif"
"*think*" = "think.gif"
"*whistle*" = "whistle.gif"