# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plugins/devconsole/devconsole.ui'
#
# Created: Mon Apr 19 15:20:27 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_devconsole(object):
    def setupUi(self, devconsole):
        devconsole.setObjectName("devconsole")
        devconsole.setEnabled(True)
        devconsole.resize(467, 491)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(devconsole.sizePolicy().hasHeightForWidth())
        devconsole.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(devconsole)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(2048, 2048))
        self.tabWidget.setObjectName("tabWidget")
        self.xmlTab = QtGui.QWidget()
        self.xmlTab.setObjectName("xmlTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.xmlTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtGui.QSplitter(self.xmlTab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.xmlOutput = QtWebKit.QWebView(self.splitter)
        self.xmlOutput.setObjectName("xmlOutput")
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self._3 = QtGui.QGridLayout(self.layoutWidget_2)
        self._3.setMargin(0)
        self._3.setSpacing(6)
        self._3.setObjectName("_3")
        self.xmlPresencePreset = QtGui.QPushButton(self.layoutWidget_2)
        self.xmlPresencePreset.setObjectName("xmlPresencePreset")
        self._3.addWidget(self.xmlPresencePreset, 0, 2, 1, 1)
        self.xmlIqPreset = QtGui.QPushButton(self.layoutWidget_2)
        self.xmlIqPreset.setObjectName("xmlIqPreset")
        self._3.addWidget(self.xmlIqPreset, 0, 3, 1, 1)
        self.xmlMessagePreset = QtGui.QPushButton(self.layoutWidget_2)
        self.xmlMessagePreset.setObjectName("xmlMessagePreset")
        self._3.addWidget(self.xmlMessagePreset, 0, 4, 1, 1)
        self.xmlInput = QtGui.QTextEdit(self.layoutWidget_2)
        self.xmlInput.setAcceptRichText(False)
        self.xmlInput.setObjectName("xmlInput")
        self._3.addWidget(self.xmlInput, 1, 0, 1, 5)
        self.xmlFilter = QtGui.QLineEdit(self.layoutWidget_2)
        self.xmlFilter.setObjectName("xmlFilter")
        self._3.addWidget(self.xmlFilter, 0, 1, 1, 1)
        self.filterLabel = QtGui.QLabel(self.layoutWidget_2)
        self.filterLabel.setObjectName("filterLabel")
        self._3.addWidget(self.filterLabel, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.splitter)
        self._2 = QtGui.QHBoxLayout()
        self._2.setSpacing(6)
        self._2.setMargin(0)
        self._2.setObjectName("_2")
        self.xmlEnableBox = QtGui.QCheckBox(self.xmlTab)
        self.xmlEnableBox.setChecked(False)
        self.xmlEnableBox.setObjectName("xmlEnableBox")
        self._2.addWidget(self.xmlEnableBox)
        spacerItem = QtGui.QSpacerItem(441, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.xmlClearButton = QtGui.QPushButton(self.xmlTab)
        self.xmlClearButton.setObjectName("xmlClearButton")
        self._2.addWidget(self.xmlClearButton)
        self.xmlSendButton = QtGui.QPushButton(self.xmlTab)
        self.xmlSendButton.setObjectName("xmlSendButton")
        self._2.addWidget(self.xmlSendButton)
        self.verticalLayout_4.addLayout(self._2)
        self.tabWidget.addTab(self.xmlTab, "")
        self.pyTab = QtGui.QWidget()
        self.pyTab.setObjectName("pyTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.pyTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._4 = QtGui.QVBoxLayout()
        self._4.setObjectName("_4")
        self.pythonOutput = QtWebKit.QWebView(self.pyTab)
        self.pythonOutput.setObjectName("pythonOutput")
        self._4.addWidget(self.pythonOutput)
        self.pythonInput = QtGui.QTextEdit(self.pyTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pythonInput.sizePolicy().hasHeightForWidth())
        self.pythonInput.setSizePolicy(sizePolicy)
        self.pythonInput.setAcceptRichText(False)
        self.pythonInput.setObjectName("pythonInput")
        self._4.addWidget(self.pythonInput)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName("_5")
        self.pythonEnableBox = QtGui.QCheckBox(self.pyTab)
        self.pythonEnableBox.setObjectName("pythonEnableBox")
        self._5.addWidget(self.pythonEnableBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._5.addItem(spacerItem1)
        self.pythonClearButton = QtGui.QPushButton(self.pyTab)
        self.pythonClearButton.setFlat(False)
        self.pythonClearButton.setObjectName("pythonClearButton")
        self._5.addWidget(self.pythonClearButton)
        self.pythonExecuteButton = QtGui.QPushButton(self.pyTab)
        self.pythonExecuteButton.setObjectName("pythonExecuteButton")
        self._5.addWidget(self.pythonExecuteButton)
        self._4.addLayout(self._5)
        self.horizontalLayout.addLayout(self._4)
        self.tabWidget.addTab(self.pyTab, "")
        self.vboxlayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.vboxlayout)
        devconsole.setCentralWidget(self.centralwidget)

        self.retranslateUi(devconsole)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(devconsole)

    def retranslateUi(self, devconsole):
        devconsole.setWindowTitle(QtGui.QApplication.translate("devconsole", "Developer console", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlPresencePreset.setText(QtGui.QApplication.translate("devconsole", "presence", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlIqPreset.setText(QtGui.QApplication.translate("devconsole", "iq", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlMessagePreset.setText(QtGui.QApplication.translate("devconsole", "message", None, QtGui.QApplication.UnicodeUTF8))
        self.filterLabel.setText(QtGui.QApplication.translate("devconsole", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlEnableBox.setText(QtGui.QApplication.translate("devconsole", "&Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlClearButton.setText(QtGui.QApplication.translate("devconsole", "Clea&r", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlSendButton.setToolTip(QtGui.QApplication.translate("devconsole", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlSendButton.setText(QtGui.QApplication.translate("devconsole", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xmlTab), QtGui.QApplication.translate("devconsole", "&XML", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonEnableBox.setText(QtGui.QApplication.translate("devconsole", "&Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonClearButton.setText(QtGui.QApplication.translate("devconsole", "Clea&r", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonExecuteButton.setToolTip(QtGui.QApplication.translate("devconsole", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonExecuteButton.setText(QtGui.QApplication.translate("devconsole", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pyTab), QtGui.QApplication.translate("devconsole", "Python &Shell", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
