# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'devconsole.ui'
#
# Created: Tue Nov 18 13:41:44 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_devconsole(object):
    def setupUi(self, devconsole):
        devconsole.setObjectName("devconsole")
        devconsole.setEnabled(True)
        devconsole.resize(467,491)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(devconsole.sizePolicy().hasHeightForWidth())
        devconsole.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(devconsole)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(-1)
        self.vboxlayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(2048,2048))
        self.tabWidget.setObjectName("tabWidget")
        self.xmlTab = QtGui.QWidget()
        self.xmlTab.setObjectName("xmlTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.xmlTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtGui.QSplitter(self.xmlTab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.xml = QtGui.QTextBrowser(self.splitter)
        self.xml.setObjectName("xml")
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self._3 = QtGui.QGridLayout(self.layoutWidget_2)
        self._3.setMargin(0)
        self._3.setSpacing(6)
        self._3.setObjectName("_3")
        self.textEdit = QtGui.QTextEdit(self.layoutWidget_2)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self._3.addWidget(self.textEdit,1,0,1,6)
        self.presence = QtGui.QPushButton(self.layoutWidget_2)
        self.presence.setObjectName("presence")
        self._3.addWidget(self.presence,0,3,1,1)
        self.iq = QtGui.QPushButton(self.layoutWidget_2)
        self.iq.setObjectName("iq")
        self._3.addWidget(self.iq,0,4,1,1)
        spacerItem = QtGui.QSpacerItem(81,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self._3.addItem(spacerItem,0,2,1,1)
        self.message = QtGui.QPushButton(self.layoutWidget_2)
        self.message.setObjectName("message")
        self._3.addWidget(self.message,0,5,1,1)
        self.verticalLayout_4.addWidget(self.splitter)
        self._2 = QtGui.QHBoxLayout()
        self._2.setSpacing(6)
        self._2.setMargin(0)
        self._2.setObjectName("_2")
        self.enable = QtGui.QCheckBox(self.xmlTab)
        self.enable.setChecked(False)
        self.enable.setObjectName("enable")
        self._2.addWidget(self.enable)
        spacerItem1 = QtGui.QSpacerItem(441,21,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem1)
        self.clear = QtGui.QPushButton(self.xmlTab)
        self.clear.setObjectName("clear")
        self._2.addWidget(self.clear)
        self.send = QtGui.QPushButton(self.xmlTab)
        self.send.setObjectName("send")
        self._2.addWidget(self.send)
        self.verticalLayout_4.addLayout(self._2)
        self.tabWidget.addTab(self.xmlTab,"")
        self.pyTab = QtGui.QWidget()
        self.pyTab.setObjectName("pyTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.pyTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._4 = QtGui.QVBoxLayout()
        self._4.setObjectName("_4")
        self.logView = QtGui.QTextBrowser(self.pyTab)
        self.logView.setObjectName("logView")
        self._4.addWidget(self.logView)
        self.input = QtGui.QTextEdit(self.pyTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setObjectName("input")
        self._4.addWidget(self.input)
        self._5 = QtGui.QHBoxLayout()
        self._5.setObjectName("_5")
        self.enableBox = QtGui.QCheckBox(self.pyTab)
        self.enableBox.setObjectName("enableBox")
        self._5.addWidget(self.enableBox)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self._5.addItem(spacerItem2)
        self.clearButton = QtGui.QPushButton(self.pyTab)
        self.clearButton.setFlat(False)
        self.clearButton.setObjectName("clearButton")
        self._5.addWidget(self.clearButton)
        self.execute = QtGui.QPushButton(self.pyTab)
        self.execute.setObjectName("execute")
        self._5.addWidget(self.execute)
        self._4.addLayout(self._5)
        self.horizontalLayout.addLayout(self._4)
        self.tabWidget.addTab(self.pyTab,"")
        self.vboxlayout.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.vboxlayout)
        devconsole.setCentralWidget(self.centralwidget)

        self.retranslateUi(devconsole)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(devconsole)

    def retranslateUi(self, devconsole):
        devconsole.setWindowTitle(QtGui.QApplication.translate("devconsole", "Developer console", None, QtGui.QApplication.UnicodeUTF8))
        self.presence.setText(QtGui.QApplication.translate("devconsole", "presence", None, QtGui.QApplication.UnicodeUTF8))
        self.iq.setText(QtGui.QApplication.translate("devconsole", "iq", None, QtGui.QApplication.UnicodeUTF8))
        self.message.setText(QtGui.QApplication.translate("devconsole", "message", None, QtGui.QApplication.UnicodeUTF8))
        self.enable.setText(QtGui.QApplication.translate("devconsole", "&Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.clear.setText(QtGui.QApplication.translate("devconsole", "Clea&r", None, QtGui.QApplication.UnicodeUTF8))
        self.send.setToolTip(QtGui.QApplication.translate("devconsole", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.send.setText(QtGui.QApplication.translate("devconsole", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xmlTab), QtGui.QApplication.translate("devconsole", "&XML", None, QtGui.QApplication.UnicodeUTF8))
        self.enableBox.setText(QtGui.QApplication.translate("devconsole", "&Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("devconsole", "Clea&r", None, QtGui.QApplication.UnicodeUTF8))
        self.execute.setToolTip(QtGui.QApplication.translate("devconsole", "Ctrl+Enter", None, QtGui.QApplication.UnicodeUTF8))
        self.execute.setText(QtGui.QApplication.translate("devconsole", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pyTab), QtGui.QApplication.translate("devconsole", "Python &Shell", None, QtGui.QApplication.UnicodeUTF8))

