# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plugins/styler/window.ui'
#
# Created: Mon Apr 19 15:20:27 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 444)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 22, 566, 401))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(464, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 1, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.cancel = QtGui.QPushButton(self.centralwidget)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 1, 1, 1, 1)
        self.tabWidge = QtGui.QTabWidget(self.centralwidget)
        self.tabWidge.setObjectName("tabWidge")
        self.tab = QtGui.QWidget()
        self.tab.setGeometry(QtCore.QRect(0, 0, 542, 327))
        self.tab.setObjectName("tab")
        self.gridLayout_25 = QtGui.QGridLayout(self.tab)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.tabWidget = QtGui.QTabWidget(self.tab)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setGeometry(QtCore.QRect(0, 0, 518, 282))
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_24 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_43 = QtGui.QLabel(self.tab_9)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_22.addWidget(self.label_43)
        self.styleDirectory = QtGui.QLineEdit(self.tab_9)
        self.styleDirectory.setObjectName("styleDirectory")
        self.horizontalLayout_22.addWidget(self.styleDirectory)
        self.gridLayout_24.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_44 = QtGui.QLabel(self.tab_9)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_23.addWidget(self.label_44)
        self.styleConfig = QtGui.QLineEdit(self.tab_9)
        self.styleConfig.setObjectName("styleConfig")
        self.horizontalLayout_23.addWidget(self.styleConfig)
        self.label_45 = QtGui.QLabel(self.tab_9)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_23.addWidget(self.label_45)
        self.gridLayout_24.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_46 = QtGui.QLabel(self.groupBox_9)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_24.addWidget(self.label_46)
        self.styleName = QtGui.QLineEdit(self.groupBox_9)
        self.styleName.setObjectName("styleName")
        self.horizontalLayout_24.addWidget(self.styleName)
        self.gridLayout_23.addLayout(self.horizontalLayout_24, 1, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_47 = QtGui.QLabel(self.groupBox_9)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_25.addWidget(self.label_47)
        self.styleAuthor = QtGui.QLineEdit(self.groupBox_9)
        self.styleAuthor.setObjectName("styleAuthor")
        self.horizontalLayout_25.addWidget(self.styleAuthor)
        self.gridLayout_23.addLayout(self.horizontalLayout_25, 2, 0, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.d = QtGui.QLabel(self.groupBox_9)
        self.d.setObjectName("d")
        self.horizontalLayout_26.addWidget(self.d)
        self.styleVersion = QtGui.QLineEdit(self.groupBox_9)
        self.styleVersion.setObjectName("styleVersion")
        self.horizontalLayout_26.addWidget(self.styleVersion)
        self.gridLayout_23.addLayout(self.horizontalLayout_26, 3, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox_9, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem1, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setGeometry(QtCore.QRect(0, 0, 518, 282))
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_27 = QtGui.QGridLayout(self.tab_10)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.groupBox_10 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_26 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.rBackgroundColor1 = QtGui.QRadioButton(self.groupBox_10)
        self.rBackgroundColor1.setChecked(True)
        self.rBackgroundColor1.setObjectName("rBackgroundColor1")
        self.horizontalLayout_27.addWidget(self.rBackgroundColor1)
        self.rBackgroundColor = QtGui.QPushButton(self.groupBox_10)
        self.rBackgroundColor.setObjectName("rBackgroundColor")
        self.horizontalLayout_27.addWidget(self.rBackgroundColor)
        spacerItem2 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.gridLayout_26.addLayout(self.horizontalLayout_27, 1, 0, 1, 2)
        self.rBackgroundImage1 = QtGui.QRadioButton(self.groupBox_10)
        self.rBackgroundImage1.setObjectName("rBackgroundImage1")
        self.gridLayout_26.addWidget(self.rBackgroundImage1, 3, 0, 1, 1)
        self.rBackgroundImage = QtGui.QLineEdit(self.groupBox_10)
        self.rBackgroundImage.setEnabled(False)
        self.rBackgroundImage.setObjectName("rBackgroundImage")
        self.gridLayout_26.addWidget(self.rBackgroundImage, 3, 1, 1, 1)
        self.label_50 = QtGui.QLabel(self.groupBox_10)
        self.label_50.setObjectName("label_50")
        self.gridLayout_26.addWidget(self.label_50, 4, 0, 1, 2)
        self.rBackground = QtGui.QCheckBox(self.groupBox_10)
        self.rBackground.setObjectName("rBackground")
        self.gridLayout_26.addWidget(self.rBackground, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_10, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 126, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, "")
        self.gridLayout_25.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidge.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0, 0, 542, 327))
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 325))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.gBackgroundColor = QtGui.QPushButton(self.groupBox_2)
        self.gBackgroundColor.setObjectName("gBackgroundColor")
        self.horizontalLayout_4.addWidget(self.gBackgroundColor)
        self.label_49 = QtGui.QLabel(self.groupBox_2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_4.addWidget(self.label_49)
        self.gBackgroundAlpha = QtGui.QSpinBox(self.groupBox_2)
        self.gBackgroundAlpha.setMaximum(255)
        self.gBackgroundAlpha.setObjectName("gBackgroundAlpha")
        self.horizontalLayout_4.addWidget(self.gBackgroundAlpha)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gHeight = QtGui.QSpinBox(self.groupBox_2)
        self.gHeight.setObjectName("gHeight")
        self.horizontalLayout.addWidget(self.gHeight)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.gIconCoordinates0 = QtGui.QSpinBox(self.groupBox_3)
        self.gIconCoordinates0.setMinimum(-500)
        self.gIconCoordinates0.setMaximum(500)
        self.gIconCoordinates0.setObjectName("gIconCoordinates0")
        self.gridLayout_3.addWidget(self.gIconCoordinates0, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.gIconCoordinates1 = QtGui.QSpinBox(self.groupBox_3)
        self.gIconCoordinates1.setMinimum(-500)
        self.gIconCoordinates1.setProperty("value", 0)
        self.gIconCoordinates1.setObjectName("gIconCoordinates1")
        self.gridLayout_3.addWidget(self.gIconCoordinates1, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.textFormat = QtGui.QTextEdit(self.groupBox)
        self.textFormat.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textFormat.setObjectName("textFormat")
        self.horizontalLayout_2.addWidget(self.textFormat)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.gFontColor = QtGui.QPushButton(self.groupBox)
        self.gFontColor.setObjectName("gFontColor")
        self.horizontalLayout_6.addWidget(self.gFontColor)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.gFontSize = QtGui.QSpinBox(self.groupBox)
        self.gFontSize.setObjectName("gFontSize")
        self.horizontalLayout_7.addWidget(self.gFontSize)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(255, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 2, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.gTextCoordinates0 = QtGui.QSpinBox(self.groupBox)
        self.gTextCoordinates0.setMinimum(-500)
        self.gTextCoordinates0.setMaximum(500)
        self.gTextCoordinates0.setObjectName("gTextCoordinates0")
        self.horizontalLayout_3.addWidget(self.gTextCoordinates0)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.gTextCoordinates1 = QtGui.QSpinBox(self.groupBox)
        self.gTextCoordinates1.setMinimum(-500)
        self.gTextCoordinates1.setProperty("value", 0)
        self.gTextCoordinates1.setObjectName("gTextCoordinates1")
        self.horizontalLayout_3.addWidget(self.gTextCoordinates1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 2, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidge.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0, 0, 542, 327))
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_18 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setGeometry(QtCore.QRect(0, 0, 518, 256))
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.uBackgroundColor = QtGui.QPushButton(self.groupBox_4)
        self.uBackgroundColor.setObjectName("uBackgroundColor")
        self.horizontalLayout_8.addWidget(self.uBackgroundColor)
        self.label_48 = QtGui.QLabel(self.groupBox_4)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_8.addWidget(self.label_48)
        self.uBackgroundAlpha = QtGui.QSpinBox(self.groupBox_4)
        self.uBackgroundAlpha.setMaximum(255)
        self.uBackgroundAlpha.setObjectName("uBackgroundAlpha")
        self.horizontalLayout_8.addWidget(self.uBackgroundAlpha)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.uHeight = QtGui.QSpinBox(self.groupBox_4)
        self.uHeight.setObjectName("uHeight")
        self.horizontalLayout_9.addWidget(self.uHeight)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_4, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setGeometry(QtCore.QRect(0, 0, 518, 256))
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.uIconCoordinates0 = QtGui.QSpinBox(self.groupBox_5)
        self.uIconCoordinates0.setMinimum(-500)
        self.uIconCoordinates0.setMaximum(500)
        self.uIconCoordinates0.setObjectName("uIconCoordinates0")
        self.gridLayout_10.addWidget(self.uIconCoordinates0, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 1, 0, 1, 1)
        self.uIconCoordinates1 = QtGui.QSpinBox(self.groupBox_5)
        self.uIconCoordinates1.setMinimum(-500)
        self.uIconCoordinates1.setProperty("value", 0)
        self.uIconCoordinates1.setObjectName("uIconCoordinates1")
        self.gridLayout_10.addWidget(self.uIconCoordinates1, 1, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_10)
        self.gridLayout_9.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 0, 0, 1, 1)
        self.uIconSize0 = QtGui.QSpinBox(self.groupBox_5)
        self.uIconSize0.setMinimum(-500)
        self.uIconSize0.setMaximum(500)
        self.uIconSize0.setObjectName("uIconSize0")
        self.gridLayout_14.addWidget(self.uIconSize0, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 1, 0, 1, 1)
        self.uIconSize1 = QtGui.QSpinBox(self.groupBox_5)
        self.uIconSize1.setMinimum(-500)
        self.uIconSize1.setProperty("value", 0)
        self.uIconSize1.setObjectName("uIconSize1")
        self.gridLayout_14.addWidget(self.uIconSize1, 1, 1, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_14)
        self.gridLayout_9.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_5, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem9, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_20 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.uTextFormat = QtGui.QTextEdit(self.groupBox_6)
        self.uTextFormat.setMaximumSize(QtCore.QSize(16777215, 50))
        self.uTextFormat.setObjectName("uTextFormat")
        self.horizontalLayout_11.addWidget(self.uTextFormat)
        self.gridLayout_11.addLayout(self.horizontalLayout_11, 0, 0, 1, 3)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.uFontColor = QtGui.QPushButton(self.groupBox_6)
        self.uFontColor.setObjectName("uFontColor")
        self.horizontalLayout_12.addWidget(self.uFontColor)
        self.gridLayout_11.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.uFontSize = QtGui.QSpinBox(self.groupBox_6)
        self.uFontSize.setObjectName("uFontSize")
        self.horizontalLayout_13.addWidget(self.uFontSize)
        self.gridLayout_11.addLayout(self.horizontalLayout_13, 1, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(255, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 1, 2, 2, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_14.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.uTextCoordinates0 = QtGui.QSpinBox(self.groupBox_6)
        self.uTextCoordinates0.setMinimum(-500)
        self.uTextCoordinates0.setMaximum(500)
        self.uTextCoordinates0.setObjectName("uTextCoordinates0")
        self.horizontalLayout_14.addWidget(self.uTextCoordinates0)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.uTextCoordinates1 = QtGui.QSpinBox(self.groupBox_6)
        self.uTextCoordinates1.setMinimum(-500)
        self.uTextCoordinates1.setProperty("value", 0)
        self.uTextCoordinates1.setObjectName("uTextCoordinates1")
        self.horizontalLayout_14.addWidget(self.uTextCoordinates1)
        self.label_41 = QtGui.QLabel(self.groupBox_6)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_14.addWidget(self.label_41)
        self.uTextCoordinates2 = QtGui.QSpinBox(self.groupBox_6)
        self.uTextCoordinates2.setMinimum(-500)
        self.uTextCoordinates2.setMaximum(500)
        self.uTextCoordinates2.setObjectName("uTextCoordinates2")
        self.horizontalLayout_14.addWidget(self.uTextCoordinates2)
        self.label_42 = QtGui.QLabel(self.groupBox_6)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_14.addWidget(self.label_42)
        self.uTextCoordinates3 = QtGui.QSpinBox(self.groupBox_6)
        self.uTextCoordinates3.setMinimum(-500)
        self.uTextCoordinates3.setMaximum(500)
        self.uTextCoordinates3.setObjectName("uTextCoordinates3")
        self.horizontalLayout_14.addWidget(self.uTextCoordinates3)
        self.gridLayout_11.addLayout(self.horizontalLayout_14, 2, 0, 1, 2)
        self.gridLayout_20.addWidget(self.groupBox_6, 0, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem12, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_21 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_26 = QtGui.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_27 = QtGui.QLabel(self.groupBox_7)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_15.addWidget(self.label_27, 0, 0, 1, 1)
        self.uAvatarCoordinates0 = QtGui.QSpinBox(self.groupBox_7)
        self.uAvatarCoordinates0.setMinimum(-500)
        self.uAvatarCoordinates0.setMaximum(500)
        self.uAvatarCoordinates0.setObjectName("uAvatarCoordinates0")
        self.gridLayout_15.addWidget(self.uAvatarCoordinates0, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_15.addWidget(self.label_28, 1, 0, 1, 1)
        self.uAvatarCoordinates1 = QtGui.QSpinBox(self.groupBox_7)
        self.uAvatarCoordinates1.setMinimum(-500)
        self.uAvatarCoordinates1.setProperty("value", 0)
        self.uAvatarCoordinates1.setObjectName("uAvatarCoordinates1")
        self.gridLayout_15.addWidget(self.uAvatarCoordinates1, 1, 1, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_15)
        self.gridLayout_13.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_17.addWidget(self.label_29)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_30 = QtGui.QLabel(self.groupBox_7)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_16.addWidget(self.label_30, 0, 0, 1, 1)
        self.uAvatarSize0 = QtGui.QSpinBox(self.groupBox_7)
        self.uAvatarSize0.setMinimum(-500)
        self.uAvatarSize0.setMaximum(500)
        self.uAvatarSize0.setObjectName("uAvatarSize0")
        self.gridLayout_16.addWidget(self.uAvatarSize0, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_7)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_16.addWidget(self.label_31, 1, 0, 1, 1)
        self.uAvatarSize1 = QtGui.QSpinBox(self.groupBox_7)
        self.uAvatarSize1.setMinimum(-500)
        self.uAvatarSize1.setProperty("value", 0)
        self.uAvatarSize1.setObjectName("uAvatarSize1")
        self.gridLayout_16.addWidget(self.uAvatarSize1, 1, 1, 1, 1)
        self.horizontalLayout_17.addLayout(self.gridLayout_16)
        self.gridLayout_13.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_7, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem14, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_22 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.groupBox_8 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_32 = QtGui.QLabel(self.groupBox_8)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        self.uStatusTextFormat = QtGui.QTextEdit(self.groupBox_8)
        self.uStatusTextFormat.setMaximumSize(QtCore.QSize(16777215, 50))
        self.uStatusTextFormat.setObjectName("uStatusTextFormat")
        self.horizontalLayout_18.addWidget(self.uStatusTextFormat)
        self.gridLayout_17.addLayout(self.horizontalLayout_18, 0, 0, 1, 3)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_33 = QtGui.QLabel(self.groupBox_8)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_19.addWidget(self.label_33)
        self.uStatusFontColor = QtGui.QPushButton(self.groupBox_8)
        self.uStatusFontColor.setObjectName("uStatusFontColor")
        self.horizontalLayout_19.addWidget(self.uStatusFontColor)
        self.gridLayout_17.addLayout(self.horizontalLayout_19, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_20.addWidget(self.label_34)
        self.uStatusFontSize = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusFontSize.setObjectName("uStatusFontSize")
        self.horizontalLayout_20.addWidget(self.uStatusFontSize)
        self.gridLayout_17.addLayout(self.horizontalLayout_20, 1, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(255, 38, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem15, 1, 2, 3, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_35 = QtGui.QLabel(self.groupBox_8)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_21.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_21.addWidget(self.label_36)
        self.uStatusTextCoordinates0 = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusTextCoordinates0.setMinimum(-500)
        self.uStatusTextCoordinates0.setMaximum(500)
        self.uStatusTextCoordinates0.setObjectName("uStatusTextCoordinates0")
        self.horizontalLayout_21.addWidget(self.uStatusTextCoordinates0)
        self.label_37 = QtGui.QLabel(self.groupBox_8)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_21.addWidget(self.label_37)
        self.uStatusTextCoordinates1 = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusTextCoordinates1.setMinimum(-500)
        self.uStatusTextCoordinates1.setProperty("value", 0)
        self.uStatusTextCoordinates1.setObjectName("uStatusTextCoordinates1")
        self.horizontalLayout_21.addWidget(self.uStatusTextCoordinates1)
        self.label_38 = QtGui.QLabel(self.groupBox_8)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_21.addWidget(self.label_38)
        self.uStatusTextCoordinates2 = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusTextCoordinates2.setMinimum(-500)
        self.uStatusTextCoordinates2.setMaximum(500)
        self.uStatusTextCoordinates2.setObjectName("uStatusTextCoordinates2")
        self.horizontalLayout_21.addWidget(self.uStatusTextCoordinates2)
        self.label_39 = QtGui.QLabel(self.groupBox_8)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_21.addWidget(self.label_39)
        self.uStatusTextCoordinates3 = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusTextCoordinates3.setMinimum(-500)
        self.uStatusTextCoordinates3.setMaximum(500)
        self.uStatusTextCoordinates3.setObjectName("uStatusTextCoordinates3")
        self.horizontalLayout_21.addWidget(self.uStatusTextCoordinates3)
        self.gridLayout_17.addLayout(self.horizontalLayout_21, 3, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.groupBox_8)
        self.label_40.setObjectName("label_40")
        self.gridLayout_17.addWidget(self.label_40, 2, 0, 1, 1)
        self.uStatusHeight = QtGui.QSpinBox(self.groupBox_8)
        self.uStatusHeight.setObjectName("uStatusHeight")
        self.gridLayout_17.addWidget(self.uStatusHeight, 2, 1, 1, 1)
        self.gridLayout_22.addWidget(self.groupBox_8, 0, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem16, 0, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem17, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.gridLayout_18.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_18.addWidget(self.comboBox, 0, 0, 1, 1)
        self.tabWidge.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidge, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 566, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 423, 566, 21))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidge.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.rBackgroundColor1, QtCore.SIGNAL("toggled(bool)"), self.rBackgroundColor.setEnabled)
        QtCore.QObject.connect(self.rBackgroundImage1, QtCore.SIGNAL("toggled(bool)"), self.rBackgroundImage.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "This style directory name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "This style variant name (config file):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", ".cfg", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "This Variant Header", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.d.setText(QtGui.QApplication.translate("MainWindow", "Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "Style Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Roster background", None, QtGui.QApplication.UnicodeUTF8))
        self.rBackgroundColor1.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.rBackgroundColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.rBackgroundImage1.setText(QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Image has to be in the same directory as this variants config file", None, QtGui.QApplication.UnicodeUTF8))
        self.rBackground.setText(QtGui.QApplication.translate("MainWindow", "Set roster background", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "Roster style", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Roster", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Background color:", None, QtGui.QApplication.UnicodeUTF8))
        self.gBackgroundColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Item icon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Icon coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Group name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Text Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Font color:", None, QtGui.QApplication.UnicodeUTF8))
        self.gFontColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Font size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Text coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Group Item", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Background color:", None, QtGui.QApplication.UnicodeUTF8))
        self.uBackgroundColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Item", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Item icon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Icon coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Icon Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Item icon", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Contact name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Text Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Font color:", None, QtGui.QApplication.UnicodeUTF8))
        self.uFontColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Font size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Text coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Contact name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Avatar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Avatar coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Avatar Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "height:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Avatar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Status message", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Text Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Font color:", None, QtGui.QApplication.UnicodeUTF8))
        self.uStatusFontColor.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Font size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Text coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "top:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Height diff:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Status message", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Default User Item", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Selected User Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidge.setTabText(self.tabWidge.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "User Item", None, QtGui.QApplication.UnicodeUTF8))

