.TH jabbim 1 "01 July 2008" "Jabbim" "Users' Manual"
.SH NAME
jabbim \- Jabber/XMPP client written in Python
.SH DESCRIPTION
Jabbim is a client for communication over XMPP/Jabber protocol written in the Python language using Qt4 and Pyxl library, which is a part of the client.

The aim of the Jabbim client is to make Jabber approachable for common people, so it is a client for common users and beginners. Because of this philosophy the Jabbim client might not suit everyone.
.SH AUTHORS
Jabbim is developed and maintained by many authors around Czech jabber server jabbim.cz. For more information, see
.I http://dev.jabbim.cz/jabbim
