import mainWindow
import rosterWidget
import status
import xmlConsole
import subscription
import chatwindow
import preferences
import joingroupchat
import filetransfer
import addcontact
import events
import rosterLiveWidget
import about
#import invitation
import servicediscovery
#import eventsFTWidget_ui
