import mainWindow
import rosterWidget
import status
import subscription
import chatwindow
import preferences
import joingroupchat
import filetransfer
import albumfiletransfer
import addcontact
import events
import rosterLiveWidget
import about
import servicediscovery
import mucbrowser
import show
import privacy
import commands
import vcardeditor
import profiles
import statuswidget_ui
import statuseditor
import emoticonswidget
#import eventsFTWidget_ui
import startchat_ui as startchat
import defaultrosterstyle
import compactrosterstyle
import webkitthemes
import addcontactng
