# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paint.ui'
#
# Created: Sat Aug 30 13:08:04 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 19, 800, 562))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(175, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.pen = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pen.sizePolicy().hasHeightForWidth())
        self.pen.setSizePolicy(sizePolicy)
        self.pen.setCheckable(True)
        self.pen.setChecked(True)
        self.pen.setAutoExclusive(True)
        self.pen.setObjectName("pen")
        self.gridLayout.addWidget(self.pen, 0, 0, 1, 1)
        self.square = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.square.sizePolicy().hasHeightForWidth())
        self.square.setSizePolicy(sizePolicy)
        self.square.setCheckable(True)
        self.square.setAutoExclusive(True)
        self.square.setObjectName("square")
        self.gridLayout.addWidget(self.square, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 431, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.sendButton = QtGui.QPushButton(self.widget)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 3, 0, 1, 1)
        self.clearButton = QtGui.QPushButton(self.widget)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainColor = QtGui.QFrame(self.centralwidget)
        self.mainColor.setMinimumSize(QtCore.QSize(38, 38))
        self.mainColor.setMaximumSize(QtCore.QSize(38, 38))
        self.mainColor.setCursor(QtCore.Qt.PointingHandCursor)
        self.mainColor.setFrameShape(QtGui.QFrame.Box)
        self.mainColor.setFrameShadow(QtGui.QFrame.Plain)
        self.mainColor.setObjectName("mainColor")
        self.horizontalLayout_2.addWidget(self.mainColor)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.color1 = QtGui.QFrame(self.centralwidget)
        self.color1.setMinimumSize(QtCore.QSize(16, 16))
        self.color1.setMaximumSize(QtCore.QSize(16, 16))
        self.color1.setCursor(QtCore.Qt.PointingHandCursor)
        self.color1.setFrameShape(QtGui.QFrame.Box)
        self.color1.setFrameShadow(QtGui.QFrame.Plain)
        self.color1.setObjectName("color1")
        self.gridLayout_2.addWidget(self.color1, 0, 0, 1, 1)
        self.color3 = QtGui.QFrame(self.centralwidget)
        self.color3.setMinimumSize(QtCore.QSize(16, 16))
        self.color3.setMaximumSize(QtCore.QSize(16, 16))
        self.color3.setCursor(QtCore.Qt.PointingHandCursor)
        self.color3.setFrameShape(QtGui.QFrame.Box)
        self.color3.setFrameShadow(QtGui.QFrame.Plain)
        self.color3.setObjectName("color3")
        self.gridLayout_2.addWidget(self.color3, 0, 1, 1, 1)
        self.color5 = QtGui.QFrame(self.centralwidget)
        self.color5.setMinimumSize(QtCore.QSize(16, 16))
        self.color5.setMaximumSize(QtCore.QSize(16, 16))
        self.color5.setCursor(QtCore.Qt.PointingHandCursor)
        self.color5.setFrameShape(QtGui.QFrame.Box)
        self.color5.setFrameShadow(QtGui.QFrame.Plain)
        self.color5.setObjectName("color5")
        self.gridLayout_2.addWidget(self.color5, 0, 2, 1, 1)
        self.color7 = QtGui.QFrame(self.centralwidget)
        self.color7.setMinimumSize(QtCore.QSize(16, 16))
        self.color7.setMaximumSize(QtCore.QSize(16, 16))
        self.color7.setCursor(QtCore.Qt.PointingHandCursor)
        self.color7.setFrameShape(QtGui.QFrame.Box)
        self.color7.setFrameShadow(QtGui.QFrame.Plain)
        self.color7.setObjectName("color7")
        self.gridLayout_2.addWidget(self.color7, 0, 3, 1, 1)
        self.color9 = QtGui.QFrame(self.centralwidget)
        self.color9.setMinimumSize(QtCore.QSize(16, 16))
        self.color9.setMaximumSize(QtCore.QSize(16, 16))
        self.color9.setCursor(QtCore.Qt.PointingHandCursor)
        self.color9.setFrameShape(QtGui.QFrame.Box)
        self.color9.setFrameShadow(QtGui.QFrame.Plain)
        self.color9.setObjectName("color9")
        self.gridLayout_2.addWidget(self.color9, 0, 4, 1, 1)
        self.color11 = QtGui.QFrame(self.centralwidget)
        self.color11.setMinimumSize(QtCore.QSize(16, 16))
        self.color11.setMaximumSize(QtCore.QSize(16, 16))
        self.color11.setCursor(QtCore.Qt.PointingHandCursor)
        self.color11.setFrameShape(QtGui.QFrame.Box)
        self.color11.setFrameShadow(QtGui.QFrame.Plain)
        self.color11.setObjectName("color11")
        self.gridLayout_2.addWidget(self.color11, 0, 5, 1, 1)
        self.color13 = QtGui.QFrame(self.centralwidget)
        self.color13.setMinimumSize(QtCore.QSize(16, 16))
        self.color13.setMaximumSize(QtCore.QSize(16, 16))
        self.color13.setCursor(QtCore.Qt.PointingHandCursor)
        self.color13.setFrameShape(QtGui.QFrame.Box)
        self.color13.setFrameShadow(QtGui.QFrame.Plain)
        self.color13.setObjectName("color13")
        self.gridLayout_2.addWidget(self.color13, 0, 6, 1, 1)
        self.color15 = QtGui.QFrame(self.centralwidget)
        self.color15.setMinimumSize(QtCore.QSize(16, 16))
        self.color15.setMaximumSize(QtCore.QSize(16, 16))
        self.color15.setCursor(QtCore.Qt.PointingHandCursor)
        self.color15.setFrameShape(QtGui.QFrame.Box)
        self.color15.setFrameShadow(QtGui.QFrame.Plain)
        self.color15.setObjectName("color15")
        self.gridLayout_2.addWidget(self.color15, 0, 7, 1, 1)
        self.color4 = QtGui.QFrame(self.centralwidget)
        self.color4.setMinimumSize(QtCore.QSize(16, 16))
        self.color4.setMaximumSize(QtCore.QSize(16, 16))
        self.color4.setCursor(QtCore.Qt.PointingHandCursor)
        self.color4.setFrameShape(QtGui.QFrame.Box)
        self.color4.setFrameShadow(QtGui.QFrame.Plain)
        self.color4.setObjectName("color4")
        self.gridLayout_2.addWidget(self.color4, 1, 1, 1, 1)
        self.color6 = QtGui.QFrame(self.centralwidget)
        self.color6.setMinimumSize(QtCore.QSize(16, 16))
        self.color6.setMaximumSize(QtCore.QSize(16, 16))
        self.color6.setCursor(QtCore.Qt.PointingHandCursor)
        self.color6.setFrameShape(QtGui.QFrame.Box)
        self.color6.setFrameShadow(QtGui.QFrame.Plain)
        self.color6.setObjectName("color6")
        self.gridLayout_2.addWidget(self.color6, 1, 2, 1, 1)
        self.color8 = QtGui.QFrame(self.centralwidget)
        self.color8.setMinimumSize(QtCore.QSize(16, 16))
        self.color8.setMaximumSize(QtCore.QSize(16, 16))
        self.color8.setCursor(QtCore.Qt.PointingHandCursor)
        self.color8.setFrameShape(QtGui.QFrame.Box)
        self.color8.setFrameShadow(QtGui.QFrame.Plain)
        self.color8.setObjectName("color8")
        self.gridLayout_2.addWidget(self.color8, 1, 3, 1, 1)
        self.color10 = QtGui.QFrame(self.centralwidget)
        self.color10.setMinimumSize(QtCore.QSize(16, 16))
        self.color10.setMaximumSize(QtCore.QSize(16, 16))
        self.color10.setCursor(QtCore.Qt.PointingHandCursor)
        self.color10.setFrameShape(QtGui.QFrame.Box)
        self.color10.setFrameShadow(QtGui.QFrame.Plain)
        self.color10.setObjectName("color10")
        self.gridLayout_2.addWidget(self.color10, 1, 4, 1, 1)
        self.color12 = QtGui.QFrame(self.centralwidget)
        self.color12.setMinimumSize(QtCore.QSize(16, 16))
        self.color12.setMaximumSize(QtCore.QSize(16, 16))
        self.color12.setCursor(QtCore.Qt.PointingHandCursor)
        self.color12.setFrameShape(QtGui.QFrame.Box)
        self.color12.setFrameShadow(QtGui.QFrame.Plain)
        self.color12.setObjectName("color12")
        self.gridLayout_2.addWidget(self.color12, 1, 5, 1, 1)
        self.color14 = QtGui.QFrame(self.centralwidget)
        self.color14.setMinimumSize(QtCore.QSize(16, 16))
        self.color14.setMaximumSize(QtCore.QSize(16, 16))
        self.color14.setCursor(QtCore.Qt.PointingHandCursor)
        self.color14.setFrameShape(QtGui.QFrame.Box)
        self.color14.setFrameShadow(QtGui.QFrame.Plain)
        self.color14.setObjectName("color14")
        self.gridLayout_2.addWidget(self.color14, 1, 6, 1, 1)
        self.color16 = QtGui.QFrame(self.centralwidget)
        self.color16.setMinimumSize(QtCore.QSize(16, 16))
        self.color16.setMaximumSize(QtCore.QSize(16, 16))
        self.color16.setCursor(QtCore.Qt.PointingHandCursor)
        self.color16.setFrameShape(QtGui.QFrame.Box)
        self.color16.setFrameShadow(QtGui.QFrame.Plain)
        self.color16.setObjectName("color16")
        self.gridLayout_2.addWidget(self.color16, 1, 7, 1, 1)
        self.color2 = QtGui.QFrame(self.centralwidget)
        self.color2.setMinimumSize(QtCore.QSize(16, 16))
        self.color2.setMaximumSize(QtCore.QSize(16, 16))
        self.color2.setCursor(QtCore.Qt.PointingHandCursor)
        self.color2.setFrameShape(QtGui.QFrame.Box)
        self.color2.setFrameShadow(QtGui.QFrame.Plain)
        self.color2.setObjectName("color2")
        self.gridLayout_2.addWidget(self.color2, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.penSize = QtGui.QSlider(self.centralwidget)
        self.penSize.setOrientation(QtCore.Qt.Horizontal)
        self.penSize.setObjectName("penSize")
        self.gridLayout_3.addWidget(self.penSize, 0, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3.addWidget(self.widget_3, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.preview = QtGui.QLabel(self.centralwidget)
        self.preview.setMinimumSize(QtCore.QSize(38, 38))
        self.preview.setMaximumSize(QtCore.QSize(38, 38))
        self.preview.setFrameShape(QtGui.QFrame.Box)
        self.preview.setObjectName("preview")
        self.gridLayout_4.addWidget(self.preview, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(182, 39, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 4, 1, 1)
        self.container = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container.sizePolicy().hasHeightForWidth())
        self.container.setSizePolicy(sizePolicy)
        self.container.setObjectName("container")
        self.gridLayout_4.addWidget(self.container, 1, 1, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 581, 800, 19))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Image paint", None, QtGui.QApplication.UnicodeUTF8))
        self.pen.setText(QtGui.QApplication.translate("MainWindow", "Pen", None, QtGui.QApplication.UnicodeUTF8))
        self.square.setText(QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pen Size", None, QtGui.QApplication.UnicodeUTF8))
        self.preview.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

