# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/preferences.ui'
#
# Created: Sat Jan 10 01:04:11 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_preferences(object):
    def setupUi(self, preferences):
        preferences.setObjectName("preferences")
        preferences.resize(676, 556)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/images/16x16/apps/jabbim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        preferences.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(preferences)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(141, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 2, 1, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.saveButton = QtGui.QPushButton(preferences)
        self.saveButton.setObjectName("saveButton")
        self.hboxlayout.addWidget(self.saveButton)
        self.applyButton = QtGui.QPushButton(preferences)
        self.applyButton.setObjectName("applyButton")
        self.hboxlayout.addWidget(self.applyButton)
        self.cancelButton = QtGui.QPushButton(preferences)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout.addWidget(self.cancelButton)
        self.gridlayout.addLayout(self.hboxlayout, 2, 2, 1, 1)
        self.listWidget = QtGui.QListWidget(preferences)
        self.listWidget.setMinimumSize(QtCore.QSize(190, 0))
        self.listWidget.setIconSize(QtCore.QSize(32, 32))
        self.listWidget.setViewMode(QtGui.QListView.ListMode)
        self.listWidget.setObjectName("listWidget")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/32x32/apps/jabbim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/32x32/categories/applications-internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/32x32/categories/conferences.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/32x32/categories/system-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/32x32/categories/v-card-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/32x32/categories/applications-graphics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon6)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/32x32/categories/applications-accessories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.listWidget)
        item.setIcon(icon7)
        self.gridlayout.addWidget(self.listWidget, 0, 0, 3, 1)
        self.profile = QtGui.QLabel(preferences)
        self.profile.setFrameShape(QtGui.QFrame.StyledPanel)
        self.profile.setAlignment(QtCore.Qt.AlignCenter)
        self.profile.setObjectName("profile")
        self.gridlayout.addWidget(self.profile, 0, 1, 1, 2)
        self.stackedWidget = QtGui.QStackedWidget(preferences)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridlayout1 = QtGui.QGridLayout(self.page_4)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_4 = QtGui.QLabel(self.page_4)
        self.label_4.setObjectName("label_4")
        self.gridlayout1.addWidget(self.label_4, 0, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.page_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout1.addWidget(self.line_2, 1, 0, 1, 1)
        self.jabbimWidget = QtGui.QWidget(self.page_4)
        self.jabbimWidget.setObjectName("jabbimWidget")
        self.gridlayout1.addWidget(self.jabbimWidget, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.userPreferences = QtGui.QWidget()
        self.userPreferences.setObjectName("userPreferences")
        self.gridlayout2 = QtGui.QGridLayout(self.userPreferences)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.connectionWidget = QtGui.QWidget(self.userPreferences)
        self.connectionWidget.setObjectName("connectionWidget")
        self.gridlayout2.addWidget(self.connectionWidget, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.userPreferences)
        self.label.setObjectName("label")
        self.gridlayout2.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.userPreferences)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout2.addWidget(self.line, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout2.addItem(spacerItem2, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.userPreferences)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridlayout3 = QtGui.QGridLayout(self.page_2)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.gridlayout3.addWidget(self.label_5, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.page_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridlayout3.addWidget(self.line_3, 1, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem3, 6, 0, 1, 1)
        self.chatWidget = QtGui.QWidget(self.page_2)
        self.chatWidget.setObjectName("chatWidget")
        self.gridlayout3.addWidget(self.chatWidget, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridlayout4 = QtGui.QGridLayout(self.page)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.line_5 = QtGui.QFrame(self.page)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridlayout4.addWidget(self.line_5, 1, 0, 1, 2)
        self.rosterWidget = QtGui.QWidget(self.page)
        self.rosterWidget.setObjectName("rosterWidget")
        self.gridlayout4.addWidget(self.rosterWidget, 2, 0, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem4, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.gridlayout4.addWidget(self.label_6, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.page)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridlayout5 = QtGui.QGridLayout(self.page_6)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")
        self.privacyWidget = QtGui.QWidget(self.page_6)
        self.privacyWidget.setObjectName("privacyWidget")
        self.gridlayout5.addWidget(self.privacyWidget, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem5, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_6)
        self.label_9.setObjectName("label_9")
        self.gridlayout5.addWidget(self.label_9, 0, 0, 1, 1)
        self.line_4 = QtGui.QFrame(self.page_6)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridlayout5.addWidget(self.line_4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_6)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridlayout6 = QtGui.QGridLayout(self.page_3)
        self.gridlayout6.setMargin(9)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")
        self.line_6 = QtGui.QFrame(self.page_3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridlayout6.addWidget(self.line_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.gridlayout6.addWidget(self.label_7, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.page_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtGui.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName("gridLayout")
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName("_2")
        self._3 = QtGui.QVBoxLayout()
        self._3.setObjectName("_3")
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self._3.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.tab_5)
        self.label_13.setObjectName("label_13")
        self._3.addWidget(self.label_13)
        self._2.addLayout(self._3)
        self._4 = QtGui.QVBoxLayout()
        self._4.setObjectName("_4")
        self.rosterStyle = QtGui.QComboBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rosterStyle.sizePolicy().hasHeightForWidth())
        self.rosterStyle.setSizePolicy(sizePolicy)
        self.rosterStyle.setMinimumSize(QtCore.QSize(130, 0))
        self.rosterStyle.setObjectName("rosterStyle")
        self._4.addWidget(self.rosterStyle)
        self.rosterVariant = QtGui.QComboBox(self.tab_5)
        self.rosterVariant.setObjectName("rosterVariant")
        self._4.addWidget(self.rosterVariant)
        self._2.addLayout(self._4)
        self.gridLayout.addLayout(self._2, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout7 = QtGui.QGridLayout(self.tab)
        self.gridlayout7.setMargin(9)
        self.gridlayout7.setSpacing(6)
        self.gridlayout7.setObjectName("gridlayout7")
        self.useThemes = QtGui.QCheckBox(self.tab)
        self.useThemes.setChecked(True)
        self.useThemes.setObjectName("useThemes")
        self.gridlayout7.addWidget(self.useThemes, 0, 0, 1, 1)
        self.themes = QtGui.QListWidget(self.tab)
        self.themes.setIconSize(QtCore.QSize(128, 128))
        self.themes.setObjectName("themes")
        self.gridlayout7.addWidget(self.themes, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout8 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout8.setObjectName("gridlayout8")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.vboxlayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName("label_11")
        self.vboxlayout.addWidget(self.label_11)
        self.hboxlayout1.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.groupchatskinStyle = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupchatskinStyle.sizePolicy().hasHeightForWidth())
        self.groupchatskinStyle.setSizePolicy(sizePolicy)
        self.groupchatskinStyle.setMinimumSize(QtCore.QSize(130, 0))
        self.groupchatskinStyle.setObjectName("groupchatskinStyle")
        self.vboxlayout1.addWidget(self.groupchatskinStyle)
        self.groupchatskinVariant = QtGui.QComboBox(self.tab_4)
        self.groupchatskinVariant.setObjectName("groupchatskinVariant")
        self.vboxlayout1.addWidget(self.groupchatskinVariant)
        self.hboxlayout1.addLayout(self.vboxlayout1)
        self.gridlayout8.addLayout(self.hboxlayout1, 0, 0, 1, 2)
        self.groupchatskinInfo = QtGui.QLabel(self.tab_4)
        self.groupchatskinInfo.setTextFormat(QtCore.Qt.RichText)
        self.groupchatskinInfo.setObjectName("groupchatskinInfo")
        self.gridlayout8.addWidget(self.groupchatskinInfo, 1, 0, 1, 2)
        self.groupchatskinPreview = QtWebKit.QWebView(self.tab_4)
        self.groupchatskinPreview.setObjectName("groupchatskinPreview")
        self.gridlayout8.addWidget(self.groupchatskinPreview, 2, 0, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(201, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout8.addItem(spacerItem7, 3, 0, 1, 1)
        self.moreGroupchatSkins = QtGui.QPushButton(self.tab_4)
        self.moreGroupchatSkins.setObjectName("moreGroupchatSkins")
        self.gridlayout8.addWidget(self.moreGroupchatSkins, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout9 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout9.setObjectName("gridlayout9")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.vboxlayout2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.vboxlayout2.addWidget(self.label_3)
        self.hboxlayout2.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.chatSkin_list = QtGui.QComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatSkin_list.sizePolicy().hasHeightForWidth())
        self.chatSkin_list.setSizePolicy(sizePolicy)
        self.chatSkin_list.setMinimumSize(QtCore.QSize(130, 0))
        self.chatSkin_list.setObjectName("chatSkin_list")
        self.vboxlayout3.addWidget(self.chatSkin_list)
        self.chatskinVariant = QtGui.QComboBox(self.tab_2)
        self.chatskinVariant.setObjectName("chatskinVariant")
        self.vboxlayout3.addWidget(self.chatskinVariant)
        self.hboxlayout2.addLayout(self.vboxlayout3)
        self.gridlayout9.addLayout(self.hboxlayout2, 0, 0, 1, 2)
        self.chatSkinInfo = QtGui.QLabel(self.tab_2)
        self.chatSkinInfo.setTextFormat(QtCore.Qt.RichText)
        self.chatSkinInfo.setObjectName("chatSkinInfo")
        self.gridlayout9.addWidget(self.chatSkinInfo, 1, 0, 1, 2)
        self.chatskinPreview = QtWebKit.QWebView(self.tab_2)
        self.chatskinPreview.setObjectName("chatskinPreview")
        self.gridlayout9.addWidget(self.chatskinPreview, 2, 0, 1, 2)
        spacerItem8 = QtGui.QSpacerItem(201, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout9.addItem(spacerItem8, 3, 0, 1, 1)
        self.moreChatSkins = QtGui.QPushButton(self.tab_2)
        self.moreChatSkins.setObjectName("moreChatSkins")
        self.gridlayout9.addWidget(self.moreChatSkins, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridlayout10 = QtGui.QGridLayout(self.tab_3)
        self.gridlayout10.setMargin(9)
        self.gridlayout10.setSpacing(6)
        self.gridlayout10.setObjectName("gridlayout10")
        spacerItem9 = QtGui.QSpacerItem(271, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout10.addItem(spacerItem9, 3, 0, 1, 1)
        self.moreEmoticons = QtGui.QPushButton(self.tab_3)
        self.moreEmoticons.setObjectName("moreEmoticons")
        self.gridlayout10.addWidget(self.moreEmoticons, 3, 1, 1, 1)
        self.emoticonsPreview = QtGui.QTextEdit(self.tab_3)
        self.emoticonsPreview.setUndoRedoEnabled(False)
        self.emoticonsPreview.setReadOnly(True)
        self.emoticonsPreview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.emoticonsPreview.setObjectName("emoticonsPreview")
        self.gridlayout10.addWidget(self.emoticonsPreview, 2, 0, 1, 2)
        self.emoticonsList = QtGui.QComboBox(self.tab_3)
        self.emoticonsList.setObjectName("emoticonsList")
        self.gridlayout10.addWidget(self.emoticonsList, 0, 0, 1, 2)
        self.emoticonsInfo = QtGui.QLabel(self.tab_3)
        self.emoticonsInfo.setTextFormat(QtCore.Qt.RichText)
        self.emoticonsInfo.setObjectName("emoticonsInfo")
        self.gridlayout10.addWidget(self.emoticonsInfo, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridlayout6.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtGui.QLabel(self.page_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 4)
        self.line_7 = QtGui.QFrame(self.page_5)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 0, 2, 4)
        self.widget = QtGui.QWidget(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addWidget(self.widget, 2, 2, 1, 2)
        self.plugins = QtGui.QTreeWidget(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.plugins.sizePolicy().hasHeightForWidth())
        self.plugins.setSizePolicy(sizePolicy)
        self.plugins.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.plugins.setAlternatingRowColors(True)
        self.plugins.setObjectName("plugins")
        self.gridLayout_2.addWidget(self.plugins, 3, 0, 1, 4)
        self.pluginDescription = QtGui.QTextBrowser(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pluginDescription.sizePolicy().hasHeightForWidth())
        self.pluginDescription.setSizePolicy(sizePolicy)
        self.pluginDescription.setMaximumSize(QtCore.QSize(16777215, 160))
        self.pluginDescription.setObjectName("pluginDescription")
        self.gridLayout_2.addWidget(self.pluginDescription, 5, 0, 1, 4)
        spacerItem10 = QtGui.QSpacerItem(261, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 7, 0, 1, 1)
        self.morePlugins = QtGui.QPushButton(self.page_5)
        self.morePlugins.setObjectName("morePlugins")
        self.gridLayout_2.addWidget(self.morePlugins, 7, 1, 1, 2)
        self.pluginConfiguration = QtGui.QPushButton(self.page_5)
        self.pluginConfiguration.setObjectName("pluginConfiguration")
        self.gridLayout_2.addWidget(self.pluginConfiguration, 7, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridlayout.addWidget(self.stackedWidget, 1, 1, 1, 2)

        self.retranslateUi(preferences)
        self.stackedWidget.setCurrentIndex(6)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), preferences.reject)
        QtCore.QObject.connect(self.saveButton, QtCore.SIGNAL("clicked()"), preferences.accept)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.useThemes, QtCore.SIGNAL("toggled(bool)"), self.themes.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(preferences)

    def retranslateUi(self, preferences):
        preferences.setWindowTitle(QtGui.QApplication.translate("preferences", "Jabbim - Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("preferences", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("preferences", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("preferences", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("preferences", "Jabbim", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("preferences", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(2).setText(QtGui.QApplication.translate("preferences", "Chat", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(3).setText(QtGui.QApplication.translate("preferences", "Roster", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(4).setText(QtGui.QApplication.translate("preferences", "Privacy", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(5).setText(QtGui.QApplication.translate("preferences", "Appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(6).setText(QtGui.QApplication.translate("preferences", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.profile.setText(QtGui.QApplication.translate("preferences", "profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Jabbim</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Connection</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\';\"><span style=\" font-size:12pt; font-weight:600;\">Chat</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Roster</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:9pt;\"><span style=\" font-size:12pt; font-weight:600;\">Privacy</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\';\"><span style=\" font-size:12pt; font-weight:600;\">View</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("preferences", "Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("preferences", "Variant:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("preferences", "Roster", None, QtGui.QApplication.UnicodeUTF8))
        self.useThemes.setText(QtGui.QApplication.translate("preferences", "Use themes", None, QtGui.QApplication.UnicodeUTF8))
        self.themes.setToolTip(QtGui.QApplication.translate("preferences", "Choose whe theme of Jabbim, then restart the client", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("preferences", "Themes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("preferences", "Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("preferences", "Variant:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupchatskinInfo.setText(QtGui.QApplication.translate("preferences", "info", None, QtGui.QApplication.UnicodeUTF8))
        self.moreGroupchatSkins.setText(QtGui.QApplication.translate("preferences", "Get more groupchat skins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("preferences", "Groupchat skin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("preferences", "Style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("preferences", "Variant:", None, QtGui.QApplication.UnicodeUTF8))
        self.chatSkinInfo.setText(QtGui.QApplication.translate("preferences", "info", None, QtGui.QApplication.UnicodeUTF8))
        self.moreChatSkins.setText(QtGui.QApplication.translate("preferences", "Get more chat skins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("preferences", "Chat skin", None, QtGui.QApplication.UnicodeUTF8))
        self.moreEmoticons.setText(QtGui.QApplication.translate("preferences", "Get more emoticons", None, QtGui.QApplication.UnicodeUTF8))
        self.emoticonsInfo.setText(QtGui.QApplication.translate("preferences", "info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("preferences", "Emoticons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("preferences", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\';\"><span style=\" font-size:12pt; font-weight:600;\">Plugins</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.plugins.setToolTip(QtGui.QApplication.translate("preferences", "Tick plugins you want to use, right click to change settings.", None, QtGui.QApplication.UnicodeUTF8))
        self.plugins.headerItem().setText(1, QtGui.QApplication.translate("preferences", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.morePlugins.setText(QtGui.QApplication.translate("preferences", "Get more plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.pluginConfiguration.setText(QtGui.QApplication.translate("preferences", "Plugin configuration", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
