my_message='<br/><br/><b>[[time]]</b> <font color="#164e6f"><b>[user]:</b></font> [message]'
message='<br/><br/><b>[[time]]</b> <font color="[foreground]"><b>[user]:</b></font> [message]'
message_for_me='<br/><br/><b>[[time]]</b> <font color="red"><b>[user]:</b> [message]</font>'
me_message='<br/><br/><b>[[time]]</b> <font color="[foreground]">* [user] [message]</font>'
my_me_message='<br/><br/><b>[[time]]</b> <font color="#164e6f">* [user] [message]</font>'
status_message='<br/><br/><b>[[time]]</b> <font color="#1eaa1e"> [message]</font>'
gc_status_message='<br/><br/><b>[[time]]</b> <font color="#1eaa1e"> [nick] is now [show] [[message]]</font>'
my_message_history='<br/><br/><font size="-1"><b>[[time]]</b> <font color="#164e6f"><b>[user]:</b></font> [message]</font>'
message_history='<br/><br/><font size="-1"><b>[[time]]</b> <font color="#a34526"><b>[user]:</b></font> [message]</font>'
message_for_me_history='<br/><br/><font size="-1"><b>[[time]]</b> <font color="red"><b>[user]:</b> [message]</font></font>'
status_message_history='<br/><br/><font size="-1"><b>[[time]]</b> <font color="#1eaa1e"> [message]</font></font>'
color1="#a34526","#FFE4E4" # tmave cervena
color2="#c000ff","#EDCDFF" # fialova
color4="#388a99","#DFFFF9" # tyrkysova
color5="#045723","#DFFFE5" # tmave zelena
color6="#7c7c7c","#F6F6F6" # seda
color7="#ff8a00","#FFFFC9" # oranzova
color8="#94452d","#FFE2D4" # tmave hneda
