my_message='<b>[[time]]</b> <font color="#1AF7FF"><b>[user]:</b></font> [message]<br/><br/>'
message='<b>[[time]]</b> <font color="#FFD59A"><b>[user]:</b></font> [message]<br/><br/>'
message_for_me='<b>[[time]]</b> <font color="red"><b>[user]:</b> [message]</font><br/><br/>'
status_message='<b>[[time]]</b> <font color="#1eaa1e"> [message]</font><br/><br/>'
gc_status_message='<b>[[time]]</b> <font color="#1eaa1e"> [nick] is now [show] [[message]]</font><br/><br/>'
my_message_history='<font size="-1"><b>[[time]]</b> <font color="#1AF7FF"><b>[user]:</b></font> [message]</font><br/><br/>'
message_history='<font size="-1"><b>[[time]]</b> <font color="#FFD59A"><b>[user]:</b></font> [message]</font><br/><br/>'
message_for_me_history='<font size="-1"><b>[[time]]</b> <font color="red"><b>[user]:</b> [message]</font></font><br/><br/>'
status_message_history='<font size="-1"><b>[[time]]</b> <font color="#1eaa1e"> [message]</font></font><br/><br/>'
