my_message='<br/> <font color="#b4b4b4"><b>[[time]]</b>[user] : [message]</font><br/>'
message='<br/><font color="#afe9af"><b>[[time]]</b><b><font color="#00aad4"> [user] :</font> </b> [message]</font><br/>'
message_for_me='<br/><font color="#00aad4"><b>[[time]]</b><b><font color="#afe9af"> [user] :</font> [message]</b></font><br/>'
status_message='<br/><font color="#1eaa1e"><b>[[time]]</b>[message]</font><br/>'
gc_status_message='<br/><font color="#1eaa1e"><b>[[time]]</b>[nick] is now [show] [[message]]</font><br/>'
my_message_history='<br/><font color="#b4b4b4" size="-1"><b>[[time]]</b>[user] : [message]</font><br/>'
message_history='<br/><font color="#afe9af" size="-1"><b>[[time]]</b><b><font color="#00aad4"> [user] :</font> </b> [message]</font><br/>'
message_for_me_history='<br/><font color="#00aad4" size="-1"><b>[[time]]</b><b><font color="#afe9af"> [user] :</font> [message]</b></font><br/>'
status_message_history='<br/><font color="#1eaa1e"" size="-1"><b>[[time]]</b>[message]</font><br/>'
