# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jabbimservicemanager.ui'
#
# Created: Sat Jul 12 14:39:05 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_jabbimServiceManager(object):
    def setupUi(self, jabbimServiceManager):
        jabbimServiceManager.setObjectName("jabbimServiceManager")
        jabbimServiceManager.resize(502,536)
        self.gridLayout = QtGui.QGridLayout(jabbimServiceManager)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(jabbimServiceManager)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label,0,0,1,4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(jabbimServiceManager)
        self.label_3.setMaximumSize(QtCore.QSize(48,1677))
        self.label_3.setPixmap(QtGui.QPixmap("images/48x48/apps/jabbim.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(jabbimServiceManager)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout,1,0,1,4)
        self.pushButton_2 = QtGui.QPushButton(jabbimServiceManager)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2,5,2,1,1)
        self.line = QtGui.QFrame(jabbimServiceManager)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line,4,0,1,3)
        self.line_2 = QtGui.QFrame(jabbimServiceManager)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2,2,0,1,3)
        self.stackedWidget = QtGui.QStackedWidget(jabbimServiceManager)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0,0,484,385))
        self.page.setObjectName("page")
        self.gridLayout_2 = QtGui.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(463,177,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem,2,0,1,1)
        self.registerService = QtGui.QGroupBox(self.page)
        self.registerService.setObjectName("registerService")
        self.gridLayout_2.addWidget(self.registerService,0,0,1,1)
        self.info = QtGui.QTextBrowser(self.page)
        self.info.setObjectName("info")
        self.gridLayout_2.addWidget(self.info,3,0,1,1)
        self.registeredServices = QtGui.QGroupBox(self.page)
        self.registeredServices.setObjectName("registeredServices")
        self.gridLayout_2.addWidget(self.registeredServices,1,0,1,1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0,0,484,385))
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setWordWrap(True)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4,0,0,1,3)
        spacerItem1 = QtGui.QSpacerItem(149,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1,1,0,1,1)
        self.registerJabberDisk = QtGui.QPushButton(self.groupBox)
        self.registerJabberDisk.setObjectName("registerJabberDisk")
        self.gridLayout_4.addWidget(self.registerJabberDisk,1,1,1,1)
        spacerItem2 = QtGui.QSpacerItem(148,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2,1,2,1,1)
        spacerItem3 = QtGui.QSpacerItem(20,265,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3,2,1,1,1)
        self.gridLayout_3.addWidget(self.groupBox,0,0,1,1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(self.page_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5,0,0,1,3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.icqNumber = QtGui.QLineEdit(self.groupBox_2)
        self.icqNumber.setObjectName("icqNumber")
        self.verticalLayout_2.addWidget(self.icqNumber)
        self.icqPassword = QtGui.QLineEdit(self.groupBox_2)
        self.icqPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.icqPassword.setObjectName("icqPassword")
        self.verticalLayout_2.addWidget(self.icqPassword)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_2,1,0,1,3)
        spacerItem4 = QtGui.QSpacerItem(149,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4,2,0,1,1)
        self.registerIcq = QtGui.QPushButton(self.groupBox_2)
        self.registerIcq.setObjectName("registerIcq")
        self.gridLayout_5.addWidget(self.registerIcq,2,1,1,1)
        spacerItem5 = QtGui.QSpacerItem(148,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5,2,2,1,1)
        spacerItem6 = QtGui.QSpacerItem(20,258,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6,3,1,1,1)
        self.gridLayout_6.addWidget(self.groupBox_2,0,0,1,1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_7 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtGui.QGroupBox(self.page_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8,0,0,1,3)
        self.dictionaries = QtGui.QTreeWidget(self.groupBox_3)
        self.dictionaries.setObjectName("dictionaries")
        self.gridLayout_8.addWidget(self.dictionaries,1,0,1,3)
        spacerItem7 = QtGui.QSpacerItem(146,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7,2,0,1,1)
        self.registerDictionaries = QtGui.QPushButton(self.groupBox_3)
        self.registerDictionaries.setObjectName("registerDictionaries")
        self.gridLayout_8.addWidget(self.registerDictionaries,2,1,1,1)
        spacerItem8 = QtGui.QSpacerItem(145,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8,2,2,1,1)
        self.gridLayout_7.addWidget(self.groupBox_3,0,0,1,1)
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget,3,0,1,4)
        self.back = QtGui.QPushButton(jabbimServiceManager)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back,5,1,1,1)
        spacerItem9 = QtGui.QSpacerItem(309,22,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9,5,0,1,1)

        self.retranslateUi(jabbimServiceManager)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_2,QtCore.SIGNAL("clicked()"),jabbimServiceManager.accept)
        QtCore.QMetaObject.connectSlotsByName(jabbimServiceManager)

    def retranslateUi(self, jabbimServiceManager):
        jabbimServiceManager.setWindowTitle(QtGui.QApplication.translate("jabbimServiceManager", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("jabbimServiceManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"><span style=\" font-size:x-large;\">Jabbim Services Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("jabbimServiceManager", "Welcome to Jabbim Services Manager which will help you to setup services available on your Jabbim server.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("jabbimServiceManager", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.registerService.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register service", None, QtGui.QApplication.UnicodeUTF8))
        self.registeredServices.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Registered services", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register Jabber Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("jabbimServiceManager", "After Registration you will see new three contacts in your roster. Every file which you send to one of these contants will be saved on your Jabber Disk. ..........", None, QtGui.QApplication.UnicodeUTF8))
        self.registerJabberDisk.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register Jabber Disk now", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register ICQ Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("jabbimServiceManager", "Please fill registration form below.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.registerIcq.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register ICQ Transport now", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Dictionaries registration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("jabbimServiceManager", "Choose dictionaries.", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionaries.headerItem().setText(0,QtGui.QApplication.translate("jabbimServiceManager", "Dictionaries", None, QtGui.QApplication.UnicodeUTF8))
        self.registerDictionaries.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register these dictionaries", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(QtGui.QApplication.translate("jabbimServiceManager", "Back", None, QtGui.QApplication.UnicodeUTF8))

