# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugins/jdm/jdw.ui'
#
# Created: Mon Dec  8 15:47:00 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_JDW(object):
    def setupUi(self, JDW):
        JDW.setObjectName("JDW")
        JDW.resize(643, 414)
        self.gridlayout = QtGui.QGridLayout(JDW)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(171, 33, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 3, 0, 1, 1)
        self.back = QtGui.QPushButton(JDW)
        self.back.setObjectName("back")
        self.gridlayout.addWidget(self.back, 3, 1, 1, 1)
        self.line_2 = QtGui.QFrame(JDW)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout.addWidget(self.line_2, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(JDW)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.pushButton = QtGui.QPushButton(JDW)
        self.pushButton.setObjectName("pushButton")
        self.gridlayout.addWidget(self.pushButton, 3, 2, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(JDW)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridlayout1 = QtGui.QGridLayout(self.page_3)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.public = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.public.sizePolicy().hasHeightForWidth())
        self.public.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("jdisk-public.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.public.setIcon(icon)
        self.public.setIconSize(QtCore.QSize(32, 32))
        self.public.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.public.setObjectName("public")
        self.gridlayout2.addWidget(self.public, 0, 0, 1, 1)
        self.private = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.private.sizePolicy().hasHeightForWidth())
        self.private.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("jdisk-private.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.private.setIcon(icon1)
        self.private.setIconSize(QtCore.QSize(32, 32))
        self.private.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.private.setObjectName("private")
        self.gridlayout2.addWidget(self.private, 0, 1, 1, 1)
        self.es = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.es.sizePolicy().hasHeightForWidth())
        self.es.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("easy_share32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.es.setIcon(icon2)
        self.es.setIconSize(QtCore.QSize(32, 32))
        self.es.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.es.setObjectName("es")
        self.gridlayout2.addWidget(self.es, 1, 1, 1, 1)
        self.album = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.album.sizePolicy().hasHeightForWidth())
        self.album.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("jalbum-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.album.setIcon(icon3)
        self.album.setIconSize(QtCore.QSize(32, 32))
        self.album.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.album.setObjectName("album")
        self.gridlayout2.addWidget(self.album, 1, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.tree = QtGui.QListWidget(self.page)
        self.tree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree.setIconSize(QtCore.QSize(32, 32))
        self.tree.setMovement(QtGui.QListView.Static)
        self.tree.setGridSize(QtCore.QSize(96, 48))
        self.tree.setViewMode(QtGui.QListView.IconMode)
        self.tree.setObjectName("tree")
        QtGui.QListWidgetItem(self.tree)
        QtGui.QListWidgetItem(self.tree)
        QtGui.QListWidgetItem(self.tree)
        self.gridLayout.addWidget(self.tree, 0, 0, 6, 1)
        self.image = QtGui.QLabel(self.page)
        self.image.setMinimumSize(QtCore.QSize(128, 0))
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 1, 1, 3)
        self.filename = QtGui.QLabel(self.page)
        self.filename.setMaximumSize(QtCore.QSize(128, 16777215))
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 1, 1, 1, 3)
        self.filesize = QtGui.QLabel(self.page)
        self.filesize.setAlignment(QtCore.Qt.AlignCenter)
        self.filesize.setObjectName("filesize")
        self.gridLayout.addWidget(self.filesize, 2, 1, 1, 3)
        self.download = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setSizeIncrement(QtCore.QSize(2, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon4)
        self.download.setIconSize(QtCore.QSize(24, 24))
        self.download.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 3, 1, 1, 1)
        self.upload = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setSizeIncrement(QtCore.QSize(2, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload.setIcon(icon5)
        self.upload.setIconSize(QtCore.QSize(24, 24))
        self.upload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.upload.setObjectName("upload")
        self.gridLayout.addWidget(self.upload, 3, 2, 1, 1)
        self.remove = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove.sizePolicy().hasHeightForWidth())
        self.remove.setSizePolicy(sizePolicy)
        self.remove.setSizeIncrement(QtCore.QSize(2, 0))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon6)
        self.remove.setIconSize(QtCore.QSize(24, 24))
        self.remove.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.remove.setObjectName("remove")
        self.gridLayout.addWidget(self.remove, 3, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 3)
        self.configuration = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configuration.sizePolicy().hasHeightForWidth())
        self.configuration.setSizePolicy(sizePolicy)
        self.configuration.setSizeIncrement(QtCore.QSize(2, 0))
        self.configuration.setIcon(icon2)
        self.configuration.setIconSize(QtCore.QSize(24, 24))
        self.configuration.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.configuration.setObjectName("configuration")
        self.gridLayout.addWidget(self.configuration, 5, 1, 1, 3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridlayout3 = QtGui.QGridLayout(self.page_2)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.prog = QtGui.QWidget(self.page_2)
        self.prog.setObjectName("prog")
        self.gridlayout3.addWidget(self.prog, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridlayout.addWidget(self.stackedWidget, 2, 0, 1, 3)

        self.retranslateUi(JDW)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), JDW.reject)
        QtCore.QMetaObject.connectSlotsByName(JDW)
        JDW.setTabOrder(self.download, self.upload)
        JDW.setTabOrder(self.upload, self.pushButton)

    def retranslateUi(self, JDW):
        JDW.setWindowTitle(JDW.translate("JDW", "Jabbim Disk Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(JDW.translate("JDW", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(JDW.translate("JDW", "Welcome to Jabbim Disk Wizard which will help you to use your Jabbim Disk account.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(JDW.translate("JDW", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.public.setText(JDW.translate("JDW", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.private.setText(JDW.translate("JDW", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.es.setText(JDW.translate("JDW", "Easyshare", None, QtGui.QApplication.UnicodeUTF8))
        self.album.setText(JDW.translate("JDW", "Album", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tree.isSortingEnabled()
        self.tree.setSortingEnabled(False)
        self.tree.item(0).setText(JDW.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.item(1).setText(JDW.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.item(2).setText(JDW.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.setSortingEnabled(__sortingEnabled)
        self.filename.setText(JDW.translate("JDW", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.filesize.setText(JDW.translate("JDW", "aaa.mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.configuration.setText(JDW.translate("JDW", "Configuration", None, QtGui.QApplication.UnicodeUTF8))

