# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plugins/jdm/jdm.ui'
#
# Created: Mon Apr 19 15:20:28 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 800, 581))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_description = QtGui.QLabel(self.centralwidget)
        self.label_description.setObjectName("label_description")
        self.horizontalLayout_2.addWidget(self.label_description)
        self.line_jid = QtGui.QLineEdit(self.centralwidget)
        self.line_jid.setMinimumSize(QtCore.QSize(0, 0))
        self.line_jid.setObjectName("line_jid")
        self.horizontalLayout_2.addWidget(self.line_jid)
        self.showMiniRoster = QtGui.QPushButton(self.centralwidget)
        self.showMiniRoster.setMaximumSize(QtCore.QSize(30, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showMiniRoster.setIcon(icon)
        self.showMiniRoster.setObjectName("showMiniRoster")
        self.horizontalLayout_2.addWidget(self.showMiniRoster)
        self.buttonHome = QtGui.QPushButton(self.centralwidget)
        self.buttonHome.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonHome.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHome.setIcon(icon1)
        self.buttonHome.setObjectName("buttonHome")
        self.horizontalLayout_2.addWidget(self.buttonHome)
        spacerItem = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.desktop = QtGui.QToolButton(self.layoutWidget_3)
        self.desktop.setObjectName("desktop")
        self.gridLayout.addWidget(self.desktop, 0, 0, 1, 1)
        self.computer = QtGui.QToolButton(self.layoutWidget_3)
        self.computer.setObjectName("computer")
        self.gridLayout.addWidget(self.computer, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(128, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.left = QtGui.QTreeView(self.layoutWidget_3)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 1, 0, 1, 3)
        self.layoutWidget_4 = QtGui.QWidget(self.splitter)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 4, 1, 1)
        self.publicButton = QtGui.QToolButton(self.layoutWidget_4)
        self.publicButton.setObjectName("publicButton")
        self.gridLayout_2.addWidget(self.publicButton, 0, 0, 1, 1)
        self.privateButton = QtGui.QToolButton(self.layoutWidget_4)
        self.privateButton.setObjectName("privateButton")
        self.gridLayout_2.addWidget(self.privateButton, 0, 1, 1, 1)
        self.album = QtGui.QToolButton(self.layoutWidget_4)
        self.album.setObjectName("album")
        self.gridLayout_2.addWidget(self.album, 0, 2, 1, 1)
        self.easyshare = QtGui.QToolButton(self.layoutWidget_4)
        self.easyshare.setObjectName("easyshare")
        self.gridLayout_2.addWidget(self.easyshare, 0, 3, 1, 1)
        self.right = QtGui.QTreeWidget(self.layoutWidget_4)
        self.right.setObjectName("right")
        self.gridLayout_2.addWidget(self.right, 1, 0, 1, 5)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtGui.QSpacerItem(318, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonUpload = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonUpload.setIcon(icon2)
        self.buttonUpload.setIconSize(QtCore.QSize(32, 32))
        self.buttonUpload.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.buttonUpload.setAutoRaise(True)
        self.buttonUpload.setObjectName("buttonUpload")
        self.horizontalLayout.addWidget(self.buttonUpload)
        self.buttonDownload = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDownload.setIcon(icon3)
        self.buttonDownload.setIconSize(QtCore.QSize(32, 32))
        self.buttonDownload.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.buttonDownload.setAutoRaise(True)
        self.buttonDownload.setObjectName("buttonDownload")
        self.horizontalLayout.addWidget(self.buttonDownload)
        self.buttonDelete = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDelete.setIcon(icon4)
        self.buttonDelete.setIconSize(QtCore.QSize(32, 32))
        self.buttonDelete.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.buttonDelete.setAutoRaise(True)
        self.buttonDelete.setObjectName("buttonDelete")
        self.horizontalLayout.addWidget(self.buttonDelete)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.statis = QtGui.QWidget(self.centralwidget)
        self.statis.setObjectName("statis")
        self.gridLayout_3.addWidget(self.statis, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 581, 800, 19))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_description.setText(QtGui.QApplication.translate("MainWindow", "Enter JID of disk owner:", None, QtGui.QApplication.UnicodeUTF8))
        self.desktop.setText(QtGui.QApplication.translate("MainWindow", "Desktop", None, QtGui.QApplication.UnicodeUTF8))
        self.computer.setText(QtGui.QApplication.translate("MainWindow", "Computer", None, QtGui.QApplication.UnicodeUTF8))
        self.publicButton.setText(QtGui.QApplication.translate("MainWindow", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.privateButton.setText(QtGui.QApplication.translate("MainWindow", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.album.setText(QtGui.QApplication.translate("MainWindow", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.easyshare.setText(QtGui.QApplication.translate("MainWindow", "Easyshare", None, QtGui.QApplication.UnicodeUTF8))
        self.right.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUpload.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDownload.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))

