# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/plugins/jdm/jdw.ui'
#
# Created: Mon Apr 19 15:20:28 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_JDW(object):
    def setupUi(self, JDW):
        JDW.setObjectName("JDW")
        JDW.resize(643, 414)
        self.gridlayout = QtGui.QGridLayout(JDW)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(171, 33, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 1, 0, 1, 1)
        self.back = QtGui.QPushButton(JDW)
        self.back.setAutoDefault(False)
        self.back.setObjectName("back")
        self.gridlayout.addWidget(self.back, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(JDW)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.gridlayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(JDW)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridlayout1 = QtGui.QGridLayout(self.page_3)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.public = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.public.sizePolicy().hasHeightForWidth())
        self.public.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("jdisk-public.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.public.setIcon(icon)
        self.public.setIconSize(QtCore.QSize(32, 32))
        self.public.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.public.setObjectName("public")
        self.gridlayout2.addWidget(self.public, 0, 0, 1, 1)
        self.private = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.private.sizePolicy().hasHeightForWidth())
        self.private.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("jdisk-private.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.private.setIcon(icon1)
        self.private.setIconSize(QtCore.QSize(32, 32))
        self.private.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.private.setObjectName("private")
        self.gridlayout2.addWidget(self.private, 0, 1, 1, 1)
        self.es = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.es.sizePolicy().hasHeightForWidth())
        self.es.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("easy_share32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.es.setIcon(icon2)
        self.es.setIconSize(QtCore.QSize(32, 32))
        self.es.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.es.setObjectName("es")
        self.gridlayout2.addWidget(self.es, 1, 1, 1, 1)
        self.album = QtGui.QToolButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.album.sizePolicy().hasHeightForWidth())
        self.album.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("jalbum-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.album.setIcon(icon3)
        self.album.setIconSize(QtCore.QSize(32, 32))
        self.album.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.album.setObjectName("album")
        self.gridlayout2.addWidget(self.album, 1, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem4, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtGui.QGridLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.leftLayout = QtGui.QGridLayout()
        self.leftLayout.setObjectName("leftLayout")
        self.path = QtGui.QLineEdit(self.page)
        self.path.setObjectName("path")
        self.leftLayout.addWidget(self.path, 0, 0, 1, 1)
        self.up = QtGui.QToolButton(self.page)
        self.up.setArrowType(QtCore.Qt.UpArrow)
        self.up.setObjectName("up")
        self.leftLayout.addWidget(self.up, 0, 1, 1, 1)
        self.tree = QtGui.QListWidget(self.page)
        self.tree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.tree.setIconSize(QtCore.QSize(32, 32))
        self.tree.setMovement(QtGui.QListView.Static)
        self.tree.setGridSize(QtCore.QSize(96, 48))
        self.tree.setViewMode(QtGui.QListView.IconMode)
        self.tree.setObjectName("tree")
        QtGui.QListWidgetItem(self.tree)
        QtGui.QListWidgetItem(self.tree)
        QtGui.QListWidgetItem(self.tree)
        self.leftLayout.addWidget(self.tree, 1, 0, 1, 2)
        self.mainLayout.addLayout(self.leftLayout, 0, 0, 1, 1)
        self.rightLayout = QtGui.QVBoxLayout()
        self.rightLayout.setObjectName("rightLayout")
        self.image = QtGui.QLabel(self.page)
        self.image.setMinimumSize(QtCore.QSize(128, 0))
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setWordWrap(True)
        self.image.setObjectName("image")
        self.rightLayout.addWidget(self.image)
        self.filename = QtGui.QLabel(self.page)
        self.filename.setMaximumSize(QtCore.QSize(155, 16777215))
        self.filename.setTextFormat(QtCore.Qt.PlainText)
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setWordWrap(True)
        self.filename.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.filename.setObjectName("filename")
        self.rightLayout.addWidget(self.filename)
        self.filesize = QtGui.QLabel(self.page)
        self.filesize.setMaximumSize(QtCore.QSize(155, 16777215))
        self.filesize.setAlignment(QtCore.Qt.AlignCenter)
        self.filesize.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.filesize.setObjectName("filesize")
        self.rightLayout.addWidget(self.filesize)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.download = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setSizeIncrement(QtCore.QSize(2, 0))
        self.download.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("document-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download.setIcon(icon4)
        self.download.setIconSize(QtCore.QSize(24, 24))
        self.download.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.download.setObjectName("download")
        self.horizontalLayout.addWidget(self.download)
        self.upload = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload.sizePolicy().hasHeightForWidth())
        self.upload.setSizePolicy(sizePolicy)
        self.upload.setSizeIncrement(QtCore.QSize(2, 0))
        self.upload.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload.setIcon(icon5)
        self.upload.setIconSize(QtCore.QSize(24, 24))
        self.upload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.upload.setObjectName("upload")
        self.horizontalLayout.addWidget(self.upload)
        self.remove = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove.sizePolicy().hasHeightForWidth())
        self.remove.setSizePolicy(sizePolicy)
        self.remove.setSizeIncrement(QtCore.QSize(2, 0))
        self.remove.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove.setIcon(icon6)
        self.remove.setIconSize(QtCore.QSize(24, 24))
        self.remove.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.remove.setObjectName("remove")
        self.horizontalLayout.addWidget(self.remove)
        self.rightLayout.addLayout(self.horizontalLayout)
        self.description = QtGui.QLabel(self.page)
        self.description.setMaximumSize(QtCore.QSize(155, 180))
        self.description.setText("")
        self.description.setTextFormat(QtCore.Qt.PlainText)
        self.description.setWordWrap(True)
        self.description.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.description.setObjectName("description")
        self.rightLayout.addWidget(self.description)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.rightLayout.addItem(spacerItem5)
        self.configuration = QtGui.QToolButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configuration.sizePolicy().hasHeightForWidth())
        self.configuration.setSizePolicy(sizePolicy)
        self.configuration.setMaximumSize(QtCore.QSize(155, 16777215))
        self.configuration.setSizeIncrement(QtCore.QSize(2, 0))
        self.configuration.setIcon(icon2)
        self.configuration.setIconSize(QtCore.QSize(24, 24))
        self.configuration.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.configuration.setObjectName("configuration")
        self.rightLayout.addWidget(self.configuration)
        self.mainLayout.addLayout(self.rightLayout, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridlayout3 = QtGui.QGridLayout(self.page_2)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.prog = QtGui.QWidget(self.page_2)
        self.prog.setObjectName("prog")
        self.gridlayout3.addWidget(self.prog, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridlayout.addWidget(self.stackedWidget, 0, 0, 1, 3)

        self.retranslateUi(JDW)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), JDW.reject)
        QtCore.QMetaObject.connectSlotsByName(JDW)
        JDW.setTabOrder(self.download, self.upload)
        JDW.setTabOrder(self.upload, self.pushButton)

    def retranslateUi(self, JDW):
        JDW.setWindowTitle(QtGui.QApplication.translate("JDW", "Jabbim Disk Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(QtGui.QApplication.translate("JDW", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("JDW", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.public.setText(QtGui.QApplication.translate("JDW", "Public", None, QtGui.QApplication.UnicodeUTF8))
        self.private.setText(QtGui.QApplication.translate("JDW", "Private", None, QtGui.QApplication.UnicodeUTF8))
        self.es.setText(QtGui.QApplication.translate("JDW", "Easyshare", None, QtGui.QApplication.UnicodeUTF8))
        self.album.setText(QtGui.QApplication.translate("JDW", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.up.setToolTip(QtGui.QApplication.translate("JDW", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.up.setText(QtGui.QApplication.translate("JDW", "...", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tree.isSortingEnabled()
        self.tree.setSortingEnabled(False)
        self.tree.item(0).setText(QtGui.QApplication.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.item(1).setText(QtGui.QApplication.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.item(2).setText(QtGui.QApplication.translate("JDW", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.tree.setSortingEnabled(__sortingEnabled)
        self.filename.setText(QtGui.QApplication.translate("JDW", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.filesize.setText(QtGui.QApplication.translate("JDW", "aaa.mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.download.setToolTip(QtGui.QApplication.translate("JDW", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.upload.setToolTip(QtGui.QApplication.translate("JDW", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.remove.setToolTip(QtGui.QApplication.translate("JDW", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.configuration.setToolTip(QtGui.QApplication.translate("JDW", "EasyShare setting", None, QtGui.QApplication.UnicodeUTF8))
        self.configuration.setText(QtGui.QApplication.translate("JDW", "Configuration", None, QtGui.QApplication.UnicodeUTF8))

