# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/wizards/jabbimservicemanager.ui'
#
# Created: Mon Apr 19 12:38:01 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_jabbimServiceManager(object):
    def setupUi(self, jabbimServiceManager):
        jabbimServiceManager.setObjectName("jabbimServiceManager")
        jabbimServiceManager.resize(502, 536)
        self.gridlayout = QtGui.QGridLayout(jabbimServiceManager)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.advanced = QtGui.QPushButton(jabbimServiceManager)
        self.advanced.setObjectName("advanced")
        self.gridlayout.addWidget(self.advanced, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(191, 33, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 5, 1, 1, 1)
        self.back = QtGui.QPushButton(jabbimServiceManager)
        self.back.setObjectName("back")
        self.gridlayout.addWidget(self.back, 5, 2, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(jabbimServiceManager)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.gridlayout1 = QtGui.QGridLayout(self.page)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        spacerItem1 = QtGui.QSpacerItem(463, 177, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 2, 0, 1, 1)
        self.registerService = QtGui.QGroupBox(self.page)
        self.registerService.setObjectName("registerService")
        self.gridlayout1.addWidget(self.registerService, 0, 0, 1, 1)
        self.info = QtGui.QTextBrowser(self.page)
        self.info.setObjectName("info")
        self.gridlayout1.addWidget(self.info, 3, 0, 1, 1)
        self.registeredServices = QtGui.QGroupBox(self.page)
        self.registeredServices.setObjectName("registeredServices")
        self.gridlayout1.addWidget(self.registeredServices, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridlayout2 = QtGui.QGridLayout(self.page_2)
        self.gridlayout2.setMargin(9)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout3 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setWordWrap(True)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.gridlayout3.addWidget(self.label_4, 0, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout3.addItem(spacerItem2, 1, 0, 1, 1)
        self.registerJabberDisk = QtGui.QPushButton(self.groupBox)
        self.registerJabberDisk.setObjectName("registerJabberDisk")
        self.gridlayout3.addWidget(self.registerJabberDisk, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout3.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 265, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem4, 2, 1, 1, 1)
        self.gridlayout2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridlayout4 = QtGui.QGridLayout(self.page_3)
        self.gridlayout4.setMargin(9)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.groupBox_2 = QtGui.QGroupBox(self.page_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout5.setMargin(9)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setWordWrap(True)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.gridlayout5.addWidget(self.label_5, 0, 0, 1, 3)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.vboxlayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.vboxlayout.addWidget(self.label_7)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.icqNumber = QtGui.QLineEdit(self.groupBox_2)
        self.icqNumber.setObjectName("icqNumber")
        self.vboxlayout1.addWidget(self.icqNumber)
        self.icqPassword = QtGui.QLineEdit(self.groupBox_2)
        self.icqPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.icqPassword.setObjectName("icqPassword")
        self.vboxlayout1.addWidget(self.icqPassword)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.gridlayout5.addLayout(self.hboxlayout, 1, 0, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem5, 2, 0, 1, 1)
        self.registerIcq = QtGui.QPushButton(self.groupBox_2)
        self.registerIcq.setObjectName("registerIcq")
        self.gridlayout5.addWidget(self.registerIcq, 2, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem6, 2, 2, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 258, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem7, 3, 1, 1, 1)
        self.gridlayout4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridlayout6 = QtGui.QGridLayout(self.page_4)
        self.gridlayout6.setMargin(9)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")
        self.groupBox_3 = QtGui.QGroupBox(self.page_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridlayout7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout7.setMargin(9)
        self.gridlayout7.setSpacing(6)
        self.gridlayout7.setObjectName("gridlayout7")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setWordWrap(True)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.gridlayout7.addWidget(self.label_8, 0, 0, 1, 3)
        self.dictionaries = QtGui.QTreeWidget(self.groupBox_3)
        self.dictionaries.setObjectName("dictionaries")
        self.gridlayout7.addWidget(self.dictionaries, 1, 0, 1, 3)
        spacerItem8 = QtGui.QSpacerItem(146, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem8, 2, 0, 1, 1)
        self.registerDictionaries = QtGui.QPushButton(self.groupBox_3)
        self.registerDictionaries.setObjectName("registerDictionaries")
        self.gridlayout7.addWidget(self.registerDictionaries, 2, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(145, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem9, 2, 2, 1, 1)
        self.gridlayout6.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.groupBox_4 = QtGui.QGroupBox(self.page_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 466, 356))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridlayout8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridlayout8.setMargin(9)
        self.gridlayout8.setSpacing(6)
        self.gridlayout8.setObjectName("gridlayout8")
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setWordWrap(True)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setObjectName("label_9")
        self.gridlayout8.addWidget(self.label_9, 0, 0, 1, 3)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.vboxlayout2.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.vboxlayout2.addWidget(self.label_11)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.icqNumber_2 = QtGui.QLineEdit(self.groupBox_4)
        self.icqNumber_2.setObjectName("icqNumber_2")
        self.vboxlayout3.addWidget(self.icqNumber_2)
        self.icqPassword_2 = QtGui.QLineEdit(self.groupBox_4)
        self.icqPassword_2.setEchoMode(QtGui.QLineEdit.Password)
        self.icqPassword_2.setObjectName("icqPassword_2")
        self.vboxlayout3.addWidget(self.icqPassword_2)
        self.hboxlayout1.addLayout(self.vboxlayout3)
        self.gridlayout8.addLayout(self.hboxlayout1, 1, 0, 1, 3)
        spacerItem10 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout8.addItem(spacerItem10, 2, 0, 1, 1)
        self.registerIcq_2 = QtGui.QPushButton(self.groupBox_4)
        self.registerIcq_2.setObjectName("registerIcq_2")
        self.gridlayout8.addWidget(self.registerIcq_2, 2, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout8.addItem(spacerItem11, 2, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 258, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout8.addItem(spacerItem12, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridlayout.addWidget(self.stackedWidget, 3, 0, 1, 4)
        self.line_2 = QtGui.QFrame(jabbimServiceManager)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout.addWidget(self.line_2, 2, 0, 1, 4)
        self.line = QtGui.QFrame(jabbimServiceManager)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout.addWidget(self.line, 4, 0, 1, 4)
        self.pushButton_2 = QtGui.QPushButton(jabbimServiceManager)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridlayout.addWidget(self.pushButton_2, 5, 3, 1, 1)
        self.label = QtGui.QLabel(jabbimServiceManager)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 4)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_3 = QtGui.QLabel(jabbimServiceManager)
        self.label_3.setMaximumSize(QtCore.QSize(48, 1677))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.hboxlayout2.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(jabbimServiceManager)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.hboxlayout2.addWidget(self.label_2)
        self.gridlayout.addLayout(self.hboxlayout2, 1, 0, 1, 4)

        self.retranslateUi(jabbimServiceManager)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), jabbimServiceManager.accept)
        QtCore.QMetaObject.connectSlotsByName(jabbimServiceManager)

    def retranslateUi(self, jabbimServiceManager):
        jabbimServiceManager.setWindowTitle(QtGui.QApplication.translate("jabbimServiceManager", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced.setText(QtGui.QApplication.translate("jabbimServiceManager", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(QtGui.QApplication.translate("jabbimServiceManager", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.registerService.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register service", None, QtGui.QApplication.UnicodeUTF8))
        self.registeredServices.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Registered services", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register Jabber Disk", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("jabbimServiceManager", "After Registration you will see new three contacts in your roster. Every file which you send to one of these contants will be saved on your Jabber Disk. ..........", None, QtGui.QApplication.UnicodeUTF8))
        self.registerJabberDisk.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register Jabber Disk now", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register ICQ Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("jabbimServiceManager", "Please fill registration form below.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.registerIcq.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register ICQ Transport now", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Dictionaries registration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("jabbimServiceManager", "Choose dictionaries.", None, QtGui.QApplication.UnicodeUTF8))
        self.dictionaries.headerItem().setText(0, QtGui.QApplication.translate("jabbimServiceManager", "Dictionaries", None, QtGui.QApplication.UnicodeUTF8))
        self.registerDictionaries.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register these dictionaries", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("jabbimServiceManager", "Register SMTP Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("jabbimServiceManager", "Please fill registration form below.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("jabbimServiceManager", "ICQ Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.registerIcq_2.setText(QtGui.QApplication.translate("jabbimServiceManager", "Register ICQ Transport now", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("jabbimServiceManager", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("jabbimServiceManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"><span style=\" font-size:x-large;\">Jabbim Services Manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("jabbimServiceManager", "Welcome to Jabbim Services Manager which will help you to setup services available on your Jabbim server.", None, QtGui.QApplication.UnicodeUTF8))

