# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/wizards/newprofile.ui'
#
# Created: Mon Apr 19 15:20:39 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_newProfile(object):
    def setupUi(self, newProfile):
        newProfile.setObjectName("newProfile")
        newProfile.resize(489, 469)
        self.gridLayout = QtGui.QGridLayout(newProfile)
        self.gridLayout.setObjectName("gridLayout")
        self.registerButton = QtGui.QPushButton(newProfile)
        self.registerButton.setAutoDefault(True)
        self.registerButton.setDefault(True)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.registerButton, 3, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(230, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(newProfile)
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.line = QtGui.QFrame(newProfile)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.cancel = QtGui.QPushButton(newProfile)
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 3, 2, 1, 1)
        self.label = QtGui.QLabel(newProfile)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.stackedWidget = QtGui.QStackedWidget(newProfile)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 471, 372))
        self.page.setObjectName("page")
        self.gridLayout_4 = QtGui.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setMaximumSize(QtCore.QSize(48, 1677))
        self.label_3.setPixmap(QtGui.QPixmap(":/images/48x48/apps/jabbim.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setWordWrap(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.createAccount = QtGui.QRadioButton(self.page)
        self.createAccount.setChecked(True)
        self.createAccount.setObjectName("createAccount")
        self.horizontalLayout_2.addWidget(self.createAccount)
        self.useAccount = QtGui.QRadioButton(self.page)
        self.useAccount.setObjectName("useAccount")
        self.horizontalLayout_2.addWidget(self.useAccount)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.stackedWidget_2 = QtGui.QStackedWidget(self.page)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 453, 262))
        self.page_3.setObjectName("page_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtGui.QGroupBox(self.page_3)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.servers = QtGui.QComboBox(self.groupBox)
        self.servers.setEditable(True)
        self.servers.setObjectName("servers")
        self.verticalLayout_2.addWidget(self.servers)
        self.nickname = QtGui.QLineEdit(self.groupBox)
        self.nickname.setObjectName("nickname")
        self.verticalLayout_2.addWidget(self.nickname)
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setEchoMode(QtGui.QLineEdit.Password)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.password2 = QtGui.QLineEdit(self.groupBox)
        self.password2.setEchoMode(QtGui.QLineEdit.Password)
        self.password2.setObjectName("password2")
        self.verticalLayout_2.addWidget(self.password2)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.jidLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jidLabel.sizePolicy().hasHeightForWidth())
        self.jidLabel.setSizePolicy(sizePolicy)
        self.jidLabel.setObjectName("jidLabel")
        self.horizontalLayout_3.addWidget(self.jidLabel)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 79, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 2, 0, 1, 1)
        self.error = QtGui.QLabel(self.groupBox)
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout_7.addWidget(self.error, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 453, 262))
        self.page_4.setObjectName("page_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.page_4)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.useJid = QtGui.QLineEdit(self.groupBox_2)
        self.useJid.setObjectName("useJid")
        self.gridLayout_5.addWidget(self.useJid, 0, 1, 1, 1)
        self.useSavepass = QtGui.QCheckBox(self.groupBox_2)
        self.useSavepass.setChecked(True)
        self.useSavepass.setObjectName("useSavepass")
        self.gridLayout_5.addWidget(self.useSavepass, 1, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 2, 0, 1, 1)
        self.usePass = QtGui.QLineEdit(self.groupBox_2)
        self.usePass.setEchoMode(QtGui.QLineEdit.Password)
        self.usePass.setObjectName("usePass")
        self.gridLayout_5.addWidget(self.usePass, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 133, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 453, 262))
        self.page_5.setObjectName("page_5")
        self.gridLayout_8 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.waitWidget = QtGui.QWidget(self.page_5)
        self.waitWidget.setObjectName("waitWidget")
        self.gridLayout_8.addWidget(self.waitWidget, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 453, 259))
        self.page_6.setObjectName("page_6")
        self.gridLayout_10 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtGui.QLabel(self.page_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.page_6)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.page_6)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.firstname = QtGui.QLineEdit(self.page_6)
        self.firstname.setObjectName("firstname")
        self.verticalLayout_4.addWidget(self.firstname)
        self.surname = QtGui.QLineEdit(self.page_6)
        self.surname.setObjectName("surname")
        self.verticalLayout_4.addWidget(self.surname)
        self.email = QtGui.QLineEdit(self.page_6)
        self.email.setObjectName("email")
        self.verticalLayout_4.addWidget(self.email)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.page_6)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.avatarLabel = QtGui.QLabel(self.groupBox_3)
        self.avatarLabel.setMinimumSize(QtCore.QSize(128, 128))
        self.avatarLabel.setText("")
        self.avatarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.gridLayout_9.addWidget(self.avatarLabel, 0, 0, 2, 1)
        self.avatars = QtGui.QListWidget(self.groupBox_3)
        self.avatars.setIconSize(QtCore.QSize(48, 48))
        self.avatars.setMovement(QtGui.QListView.Static)
        self.avatars.setFlow(QtGui.QListView.TopToBottom)
        self.avatars.setViewMode(QtGui.QListView.IconMode)
        self.avatars.setWordWrap(True)
        self.avatars.setObjectName("avatars")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/avatars/sunset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/avatars/ship.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/avatars/kitten.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/avatars/dog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/avatars/car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/avatars/ball.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item = QtGui.QListWidgetItem(self.avatars)
        item.setIcon(icon5)
        self.gridLayout_9.addWidget(self.avatars, 0, 1, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(156, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 2, 1, 1)
        self.loadAvatar = QtGui.QPushButton(self.groupBox_3)
        self.loadAvatar.setObjectName("loadAvatar")
        self.gridLayout_9.addWidget(self.loadAvatar, 1, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.gridLayout_4.addWidget(self.stackedWidget_2, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 471, 362))
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 4)

        self.retranslateUi(newProfile)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(3)
        QtCore.QObject.connect(self.useSavepass, QtCore.SIGNAL("clicked(bool)"), self.usePass.setVisible)
        QtCore.QObject.connect(self.useSavepass, QtCore.SIGNAL("clicked(bool)"), self.label_5.setVisible)
        QtCore.QObject.connect(self.cancel, QtCore.SIGNAL("clicked()"), newProfile.reject)
        QtCore.QObject.connect(self.registerButton, QtCore.SIGNAL("clicked()"), newProfile.accept)
        QtCore.QMetaObject.connectSlotsByName(newProfile)

    def retranslateUi(self, newProfile):
        newProfile.setWindowTitle(QtGui.QApplication.translate("newProfile", "New Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.registerButton.setText(QtGui.QApplication.translate("newProfile", "Register", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("newProfile", "Online help", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("newProfile", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("newProfile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"><span style=\" font-size:x-large;\">New Jabbim Profile</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("newProfile", "Welcome to the open world of Jabber. This wizzard will help you with creating your account, so you can chat with your friends in no time.", None, QtGui.QApplication.UnicodeUTF8))
        self.createAccount.setText(QtGui.QApplication.translate("newProfile", "Create new Jabber account", None, QtGui.QApplication.UnicodeUTF8))
        self.useAccount.setText(QtGui.QApplication.translate("newProfile", "Use existing Jabber account", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("newProfile", "Register new Jabber Account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("newProfile", "Jabber server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("newProfile", "Nickname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("newProfile", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("newProfile", "Password again:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("newProfile", "Your Jabber ID will be:", None, QtGui.QApplication.UnicodeUTF8))
        self.jidLabel.setText(QtGui.QApplication.translate("newProfile", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">example@jabbim.cz</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("newProfile", "Use existing Jabber Account", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("newProfile", "Jabber ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.useSavepass.setText(QtGui.QApplication.translate("newProfile", "Save password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("newProfile", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("newProfile", "First name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("newProfile", "Surname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("newProfile", "Email:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("newProfile", "Avatar", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.avatars.isSortingEnabled()
        self.avatars.setSortingEnabled(False)
        self.avatars.item(0).setText(QtGui.QApplication.translate("newProfile", "Sunset", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.item(1).setText(QtGui.QApplication.translate("newProfile", "Ship", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.item(2).setText(QtGui.QApplication.translate("newProfile", "Kitten", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.item(3).setText(QtGui.QApplication.translate("newProfile", "Dog", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.item(4).setText(QtGui.QApplication.translate("newProfile", "Car", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.item(5).setText(QtGui.QApplication.translate("newProfile", "Ball", None, QtGui.QApplication.UnicodeUTF8))
        self.avatars.setSortingEnabled(__sortingEnabled)
        self.loadAvatar.setText(QtGui.QApplication.translate("newProfile", "Load avatar from file", None, QtGui.QApplication.UnicodeUTF8))

