[roster]
base="" 			# Background
alternateBase="" 	# Alternative background
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text
group="#666666"			# Group background
groupText="#FFFFFF"		# Group text

[chatwindow]
[chatwidget]