[roster]
alternateBase="#000000" 	# Alternative background
alternateBaseAlpha="40" 	# Alternative background alpha
bgImage="palettes/default/texture.png"
base="" 			# Background
baseAlpha="1" 			# Background
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text
added="#99CCFF"
addedAlpha="60"
add="#990000"
addAlpha="60"
group="#666666"			# Group background
groupText="#FFFFFF"		# Group text

[chatwindow]
#bgImage="palettes/default/texture.png"
[chatwidget]
#bgImage="palettes/default/texture.png"
[chatwindowTab]
bgImage="palettes/default/texture.png"
windowAlpha="1" 			# Background
[tooltip]
window="#FFFAEE" 			# Background