[roster]
base="" 			# Background
baseAlpha="0" 			# Background
alternateBase="#000000" 	# Alternative background
alternateBaseAlpha="40" 	# Alternative background alpha
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text
group="#666666"			# Group background
groupText="#FFFFFF"		# Group text

[chatwindow]
[chatwidget]