[roster]
base="" 			# Background
baseAlpha="50" 	# Alternative background
alternateBase="" 	# Alternative background
alternateBaseAlpha="50" 	# Alternative background
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text
group="#932A2B"			# Group background
groupText="#FFFFFF"		# Group text

[chatwindow]
base="#FCFCE8" 			# Background
alternateBase="" 	# Alternative background
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text

[chatwidget]
base="#FCFCE8" 			# Background
alternateBase="" 	# Alternative background
text=""				# Foreground color
highlight=""		# Highlighted
highlightedText=""	# Highlighted text