# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/widgets/addcontactng.ui'
#
# Created: Mon Apr 19 15:20:32 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_addContact(object):
    def setupUi(self, addContact):
        addContact.setObjectName("addContact")
        addContact.resize(443, 512)
        self.gridlayout = QtGui.QGridLayout(addContact)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_2 = QtGui.QLabel(addContact)
        self.label_2.setObjectName("label_2")
        self.hboxlayout.addWidget(self.label_2)
        self.service = QtGui.QComboBox(addContact)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7), QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service.sizePolicy().hasHeightForWidth())
        self.service.setSizePolicy(sizePolicy)
        self.service.setObjectName("service")
        self.hboxlayout.addWidget(self.service)
        self.gridlayout.addLayout(self.hboxlayout, 2, 0, 1, 3)
        self._tabBar = QtGui.QWidget(addContact)
        self._tabBar.setObjectName("_tabBar")
        self.gridlayout.addWidget(self._tabBar, 1, 0, 1, 3)
        self.addToRoster = QtGui.QPushButton(addContact)
        self.addToRoster.setAutoDefault(False)
        self.addToRoster.setObjectName("addToRoster")
        self.gridlayout.addWidget(self.addToRoster, 9, 1, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.searchLabel = QtGui.QLabel(addContact)
        self.searchLabel.setObjectName("searchLabel")
        self.hboxlayout1.addWidget(self.searchLabel)
        self.lineEdit = QtGui.QLineEdit(addContact)
        self.lineEdit.setObjectName("lineEdit")
        self.hboxlayout1.addWidget(self.lineEdit)
        self.search = QtGui.QPushButton(addContact)
        self.search.setObjectName("search")
        self.hboxlayout1.addWidget(self.search)
        self.add = QtGui.QPushButton(addContact)
        self.add.setObjectName("add")
        self.hboxlayout1.addWidget(self.add)
        self.gridlayout.addLayout(self.hboxlayout1, 4, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 8, 0, 1, 1)
        self.label = QtGui.QLabel(addContact)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 3)
        self.treeWidget = QtGui.QTreeWidget(addContact)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7), QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setObjectName("treeWidget")
        self.gridlayout.addWidget(self.treeWidget, 7, 0, 1, 3)
        self.description = QtGui.QTextBrowser(addContact)
        self.description.setMaximumSize(QtCore.QSize(16777215, 70))
        self.description.setObjectName("description")
        self.gridlayout.addWidget(self.description, 3, 0, 1, 3)
        self.empty = QtGui.QLabel(addContact)
        self.empty.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.empty.setObjectName("empty")
        self.gridlayout.addWidget(self.empty, 6, 0, 1, 3)
        self.pushButton = QtGui.QPushButton(addContact)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.gridlayout.addWidget(self.pushButton, 9, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(218, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.picture = QtGui.QLabel(addContact)
        self.picture.setObjectName("picture")
        self.gridlayout.addWidget(self.picture, 5, 0, 1, 3)

        self.retranslateUi(addContact)
        QtCore.QObject.connect(self.lineEdit, QtCore.SIGNAL("returnPressed()"), self.search.click)
        QtCore.QObject.connect(self.addToRoster, QtCore.SIGNAL("clicked()"), addContact.accept)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), addContact.reject)
        QtCore.QMetaObject.connectSlotsByName(addContact)

    def retranslateUi(self, addContact):
        addContact.setWindowTitle(QtGui.QApplication.translate("addContact", "Find user", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("addContact", "Service:", None, QtGui.QApplication.UnicodeUTF8))
        self.addToRoster.setText(QtGui.QApplication.translate("addContact", "Add to roster", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLabel.setText(QtGui.QApplication.translate("addContact", "User:", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setText(QtGui.QApplication.translate("addContact", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("addContact", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("addContact", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><h2>Find user</h2></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("addContact", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.empty.setText(QtGui.QApplication.translate("addContact", "No contact matching your criteria was found", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("addContact", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

