# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/widgets/preferences_bookmarks.ui'
#
# Created: Mon Apr 19 15:20:34 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_editbookmark(object):
    def setupUi(self, editbookmark):
        editbookmark.setObjectName("editbookmark")
        editbookmark.resize(262, 243)
        icon = QtGui.QIcon()
        icon.addFile(":/images/16x16/apps/jabbim.png")
        editbookmark.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(editbookmark)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(191, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pushButton = QtGui.QPushButton(editbookmark)
        self.pushButton.setObjectName("pushButton")
        self.hboxlayout.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(editbookmark)
        self.pushButton_2.setObjectName("pushButton_2")
        self.hboxlayout.addWidget(self.pushButton_2)
        self.gridlayout.addLayout(self.hboxlayout, 3, 1, 1, 2)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtGui.QLabel(editbookmark)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.label_3 = QtGui.QLabel(editbookmark)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(editbookmark)
        self.label_4.setObjectName("label_4")
        self.vboxlayout.addWidget(self.label_4)
        self.label_2 = QtGui.QLabel(editbookmark)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(editbookmark)
        self.label_5.setObjectName("label_5")
        self.vboxlayout.addWidget(self.label_5)
        self.hboxlayout1.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.room = QtGui.QLineEdit(editbookmark)
        self.room.setObjectName("room")
        self.vboxlayout1.addWidget(self.room)
        self.server = QtGui.QLineEdit(editbookmark)
        self.server.setObjectName("server")
        self.vboxlayout1.addWidget(self.server)
        self.name = QtGui.QLineEdit(editbookmark)
        self.name.setObjectName("name")
        self.vboxlayout1.addWidget(self.name)
        self.nickname = QtGui.QLineEdit(editbookmark)
        self.nickname.setObjectName("nickname")
        self.vboxlayout1.addWidget(self.nickname)
        self.password = QtGui.QLineEdit(editbookmark)
        self.password.setObjectName("password")
        self.vboxlayout1.addWidget(self.password)
        self.hboxlayout1.addLayout(self.vboxlayout1)
        self.gridlayout.addLayout(self.hboxlayout1, 0, 0, 1, 3)
        self.autojoin = QtGui.QCheckBox(editbookmark)
        self.autojoin.setObjectName("autojoin")
        self.gridlayout.addWidget(self.autojoin, 1, 2, 1, 1)
        self.line = QtGui.QFrame(editbookmark)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout.addWidget(self.line, 2, 0, 1, 3)

        self.retranslateUi(editbookmark)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), editbookmark.accept)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL("clicked()"), editbookmark.reject)
        QtCore.QMetaObject.connectSlotsByName(editbookmark)

    def retranslateUi(self, editbookmark):
        editbookmark.setWindowTitle(QtGui.QApplication.translate("editbookmark", "Edit bookmark", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("editbookmark", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("editbookmark", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("editbookmark", "Room:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("editbookmark", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("editbookmark", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("editbookmark", "Nickname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("editbookmark", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.room.setToolTip(QtGui.QApplication.translate("editbookmark", "The name of the room", None, QtGui.QApplication.UnicodeUTF8))
        self.server.setToolTip(QtGui.QApplication.translate("editbookmark", "The server where the chat room is (e.g. conf.netlab.cz)", None, QtGui.QApplication.UnicodeUTF8))
        self.name.setToolTip(QtGui.QApplication.translate("editbookmark", "What do you want to see in your bookmark list", None, QtGui.QApplication.UnicodeUTF8))
        self.nickname.setToolTip(QtGui.QApplication.translate("editbookmark", "Enter your nickname", None, QtGui.QApplication.UnicodeUTF8))
        self.password.setToolTip(QtGui.QApplication.translate("editbookmark", "Password is used when room is locked", None, QtGui.QApplication.UnicodeUTF8))
        self.autojoin.setToolTip(QtGui.QApplication.translate("editbookmark", "If you check this, Jabbim will connect you after each start of client", None, QtGui.QApplication.UnicodeUTF8))
        self.autojoin.setText(QtGui.QApplication.translate("editbookmark", "Autojoin", None, QtGui.QApplication.UnicodeUTF8))

