# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/widgets/chat/chatwidget.ui'
#
# Created: Mon Apr 19 15:20:31 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_chatwidget(object):
    def setupUi(self, chatwidget):
        chatwidget.setObjectName("chatwidget")
        chatwidget.resize(652, 414)
        chatwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout = QtGui.QGridLayout(chatwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtGui.QWidget(chatwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.avatar = QtGui.QLabel(self.widget)
        self.avatar.setText("")
        self.avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar.setObjectName("avatar")
        self.horizontalLayout_3.addWidget(self.avatar)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(8, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chatstate = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatstate.sizePolicy().hasHeightForWidth())
        self.chatstate.setSizePolicy(sizePolicy)
        self.chatstate.setText("")
        self.chatstate.setAlignment(QtCore.Qt.AlignCenter)
        self.chatstate.setObjectName("chatstate")
        self.horizontalLayout.addWidget(self.chatstate)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.metaLabel = QtGui.QLabel(self.widget)
        self.metaLabel.setObjectName("metaLabel")
        self.horizontalLayout_2.addWidget(self.metaLabel)
        self.metaButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.metaButton.sizePolicy().hasHeightForWidth())
        self.metaButton.setSizePolicy(sizePolicy)
        self.metaButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.metaButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.metaButton.setArrowType(QtCore.Qt.NoArrow)
        self.metaButton.setObjectName("metaButton")
        self.horizontalLayout_2.addWidget(self.metaButton)
        self.resourceLabel = QtGui.QLabel(self.widget)
        self.resourceLabel.setObjectName("resourceLabel")
        self.horizontalLayout_2.addWidget(self.resourceLabel)
        self.resourceButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resourceButton.sizePolicy().hasHeightForWidth())
        self.resourceButton.setSizePolicy(sizePolicy)
        self.resourceButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.resourceButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.resourceButton.setArrowType(QtCore.Qt.NoArrow)
        self.resourceButton.setObjectName("resourceButton")
        self.horizontalLayout_2.addWidget(self.resourceButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.ftwidget = QtGui.QWidget(self.widget)
        self.ftwidget.setObjectName("ftwidget")
        self.horizontalLayout_2.addWidget(self.ftwidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(1, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.cool = QtGui.QWidget(self.widget)
        self.cool.setObjectName("cool")
        self.horizontalLayout_3.addWidget(self.cool)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(chatwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.splitter_4 = QtGui.QSplitter(self.splitter)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.viewWidget = QtGui.QWidget(self.splitter_4)
        self.viewWidget.setMinimumSize(QtCore.QSize(0, 10))
        self.viewWidget.setObjectName("viewWidget")
        self.pluginWidget = QtGui.QWidget(self.splitter_4)
        self.pluginWidget.setMinimumSize(QtCore.QSize(32, 0))
        self.pluginWidget.setMaximumSize(QtCore.QSize(32, 16777215))
        self.pluginWidget.setObjectName("pluginWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.pluginWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton = QtGui.QToolButton(self.pluginWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setCheckable(True)
        self.toolButton.setArrowType(QtCore.Qt.UpArrow)
        self.toolButton.setObjectName("toolButton")
        self.verticalLayout.addWidget(self.toolButton)
        self.line_2 = QtGui.QFrame(self.pluginWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.selfAvatar = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selfAvatar.sizePolicy().hasHeightForWidth())
        self.selfAvatar.setSizePolicy(sizePolicy)
        self.selfAvatar.setText("")
        self.selfAvatar.setObjectName("selfAvatar")
        self.hboxlayout.addWidget(self.selfAvatar)
        self.lineWidget = QtGui.QWidget(self.layoutWidget)
        self.lineWidget.setMinimumSize(QtCore.QSize(0, 10))
        self.lineWidget.setObjectName("lineWidget")
        self.hboxlayout.addWidget(self.lineWidget)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem2 = QtGui.QSpacerItem(111, 29, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.linkButton = QtGui.QToolButton(self.layoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/16x16/actions/anchor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkButton.setIcon(icon)
        self.linkButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.linkButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.linkButton.setObjectName("linkButton")
        self.hboxlayout1.addWidget(self.linkButton)
        self.boldButton = QtGui.QToolButton(self.layoutWidget)
        self.boldButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldButton.setIcon(icon1)
        self.boldButton.setCheckable(True)
        self.boldButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.boldButton.setObjectName("boldButton")
        self.hboxlayout1.addWidget(self.boldButton)
        self.italicButton = QtGui.QToolButton(self.layoutWidget)
        self.italicButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicButton.setIcon(icon2)
        self.italicButton.setCheckable(True)
        self.italicButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.italicButton.setObjectName("italicButton")
        self.hboxlayout1.addWidget(self.italicButton)
        self.underlineButton = QtGui.QToolButton(self.layoutWidget)
        self.underlineButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/16x16/actions/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlineButton.setIcon(icon3)
        self.underlineButton.setCheckable(True)
        self.underlineButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.underlineButton.setObjectName("underlineButton")
        self.hboxlayout1.addWidget(self.underlineButton)
        self.colorButton = QtGui.QToolButton(self.layoutWidget)
        self.colorButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.colorButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.colorButton.setObjectName("colorButton")
        self.hboxlayout1.addWidget(self.colorButton)
        self.backgroundButton = QtGui.QToolButton(self.layoutWidget)
        self.backgroundButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.backgroundButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.backgroundButton.setObjectName("backgroundButton")
        self.hboxlayout1.addWidget(self.backgroundButton)
        self.fontSize = QtGui.QComboBox(self.layoutWidget)
        self.fontSize.setObjectName("fontSize")
        self.hboxlayout1.addWidget(self.fontSize)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout1.addWidget(self.line)
        self.smileys = QtGui.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/16x16/emotes/biggrin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smileys.setIcon(icon4)
        self.smileys.setCheckable(True)
        self.smileys.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.smileys.setObjectName("smileys")
        self.hboxlayout1.addWidget(self.smileys)
        self.sendButton = QtGui.QPushButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/16x16/actions/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sendButton.setIcon(icon5)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout1.addWidget(self.sendButton)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)

        self.retranslateUi(chatwidget)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL("toggled(bool)"), self.widget.setHidden)
        QtCore.QMetaObject.connectSlotsByName(chatwidget)

    def retranslateUi(self, chatwidget):
        chatwidget.setWindowTitle(QtGui.QApplication.translate("chatwidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.metaLabel.setText(QtGui.QApplication.translate("chatwidget", "Metacontact:", None, QtGui.QApplication.UnicodeUTF8))
        self.resourceLabel.setText(QtGui.QApplication.translate("chatwidget", "Resource:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("chatwidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.linkButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Anchor", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setText(QtGui.QApplication.translate("chatwidget", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setText(QtGui.QApplication.translate("chatwidget", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setText(QtGui.QApplication.translate("chatwidget", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.colorButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Font color", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Background color", None, QtGui.QApplication.UnicodeUTF8))
        self.fontSize.setToolTip(QtGui.QApplication.translate("chatwidget", "Font size", None, QtGui.QApplication.UnicodeUTF8))
        self.smileys.setToolTip(QtGui.QApplication.translate("chatwidget", "Emoticons", None, QtGui.QApplication.UnicodeUTF8))
        self.smileys.setText(QtGui.QApplication.translate("chatwidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setToolTip(QtGui.QApplication.translate("chatwidget", "Send message", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("chatwidget", "&Send", None, QtGui.QApplication.UnicodeUTF8))

