# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/widgets/chat/groupchatwidget.ui'
#
# Created: Mon Apr 19 15:20:31 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_groupchatwidget(object):
    def setupUi(self, groupchatwidget):
        groupchatwidget.setObjectName("groupchatwidget")
        groupchatwidget.resize(536, 408)
        groupchatwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridlayout = QtGui.QGridLayout(groupchatwidget)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.splitter_3 = QtGui.QSplitter(groupchatwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget = QtGui.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName("layoutWidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.disco_info = QtGui.QLabel(self.layoutWidget)
        self.disco_info.setText("")
        self.disco_info.setObjectName("disco_info")
        self.vboxlayout.addWidget(self.disco_info)
        self.info = QtGui.QTextBrowser(self.layoutWidget)
        self.info.setMinimumSize(QtCore.QSize(0, 1))
        self.info.setOpenExternalLinks(True)
        self.info.setObjectName("info")
        self.vboxlayout.addWidget(self.info)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.viewWidget = QtGui.QWidget(self.splitter)
        self.viewWidget.setObjectName("viewWidget")
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridlayout1 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.linkButton = QtGui.QToolButton(self.layoutWidget1)
        icon = QtGui.QIcon()
        icon.addFile(":/images/16x16/actions/anchor.png")
        self.linkButton.setIcon(icon)
        self.linkButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.linkButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.linkButton.setObjectName("linkButton")
        self.hboxlayout.addWidget(self.linkButton)
        self.boldButton = QtGui.QToolButton(self.layoutWidget1)
        self.boldButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addFile(":/images/16x16/actions/format-text-bold.png")
        self.boldButton.setIcon(icon1)
        self.boldButton.setCheckable(True)
        self.boldButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.boldButton.setObjectName("boldButton")
        self.hboxlayout.addWidget(self.boldButton)
        self.italicButton = QtGui.QToolButton(self.layoutWidget1)
        self.italicButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addFile(":/images/16x16/actions/format-text-italic.png")
        self.italicButton.setIcon(icon2)
        self.italicButton.setCheckable(True)
        self.italicButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.italicButton.setObjectName("italicButton")
        self.hboxlayout.addWidget(self.italicButton)
        self.underlineButton = QtGui.QToolButton(self.layoutWidget1)
        self.underlineButton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addFile(":/images/16x16/actions/format-text-underline.png")
        self.underlineButton.setIcon(icon3)
        self.underlineButton.setCheckable(True)
        self.underlineButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.underlineButton.setObjectName("underlineButton")
        self.hboxlayout.addWidget(self.underlineButton)
        self.colorButton = QtGui.QToolButton(self.layoutWidget1)
        self.colorButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.colorButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.colorButton.setObjectName("colorButton")
        self.hboxlayout.addWidget(self.colorButton)
        self.backgroundButton = QtGui.QToolButton(self.layoutWidget1)
        self.backgroundButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.backgroundButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.backgroundButton.setObjectName("backgroundButton")
        self.hboxlayout.addWidget(self.backgroundButton)
        self.fontSize = QtGui.QComboBox(self.layoutWidget1)
        self.fontSize.setObjectName("fontSize")
        self.hboxlayout.addWidget(self.fontSize)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.smileys = QtGui.QToolButton(self.layoutWidget1)
        icon4 = QtGui.QIcon()
        icon4.addFile(":/images/16x16/emotes/biggrin.png")
        self.smileys.setIcon(icon4)
        self.smileys.setCheckable(True)
        self.smileys.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.smileys.setObjectName("smileys")
        self.hboxlayout.addWidget(self.smileys)
        self.sendButton = QtGui.QToolButton(self.layoutWidget1)
        icon5 = QtGui.QIcon()
        icon5.addFile(":/images/16x16/actions/send.png")
        self.sendButton.setIcon(icon5)
        self.sendButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout.addWidget(self.sendButton)
        self.gridlayout1.addLayout(self.hboxlayout, 1, 0, 1, 2)
        self.selfAvatar = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0), QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selfAvatar.sizePolicy().hasHeightForWidth())
        self.selfAvatar.setSizePolicy(sizePolicy)
        self.selfAvatar.setText("")
        self.selfAvatar.setObjectName("selfAvatar")
        self.gridlayout1.addWidget(self.selfAvatar, 0, 0, 1, 1)
        self.lineWidget = QtGui.QWidget(self.layoutWidget1)
        self.lineWidget.setMinimumSize(QtCore.QSize(0, 10))
        self.lineWidget.setObjectName("lineWidget")
        self.gridlayout1.addWidget(self.lineWidget, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.users = QtGui.QTreeWidget(self.layoutWidget2)
        self.users.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.users.setIconSize(QtCore.QSize(32, 32))
        self.users.setIndentation(0)
        self.users.setRootIsDecorated(False)
        self.users.setObjectName("users")
        self.vboxlayout1.addWidget(self.users)
        self.pluginWidget = QtGui.QWidget(self.layoutWidget2)
        self.pluginWidget.setObjectName("pluginWidget")
        self.vboxlayout1.addWidget(self.pluginWidget)
        self.gridlayout.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.retranslateUi(groupchatwidget)
        QtCore.QMetaObject.connectSlotsByName(groupchatwidget)

    def retranslateUi(self, groupchatwidget):
        groupchatwidget.setWindowTitle(QtGui.QApplication.translate("groupchatwidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.info.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Every multi-user chat can have topic of its discussion", None, QtGui.QApplication.UnicodeUTF8))
        self.linkButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Anchor", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.boldButton.setText(QtGui.QApplication.translate("groupchatwidget", "Bold", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.italicButton.setText(QtGui.QApplication.translate("groupchatwidget", "Italic", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.underlineButton.setText(QtGui.QApplication.translate("groupchatwidget", "Underline", None, QtGui.QApplication.UnicodeUTF8))
        self.colorButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Font color", None, QtGui.QApplication.UnicodeUTF8))
        self.backgroundButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Background color", None, QtGui.QApplication.UnicodeUTF8))
        self.fontSize.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Font size", None, QtGui.QApplication.UnicodeUTF8))
        self.smileys.setToolTip(QtGui.QApplication.translate("groupchatwidget", "You can add emoticons by clicking here", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setToolTip(QtGui.QApplication.translate("groupchatwidget", "Send Message", None, QtGui.QApplication.UnicodeUTF8))
        self.sendButton.setText(QtGui.QApplication.translate("groupchatwidget", "&Send", None, QtGui.QApplication.UnicodeUTF8))
        self.users.headerItem().setText(0, QtGui.QApplication.translate("groupchatwidget", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.users.headerItem().setText(1, QtGui.QApplication.translate("groupchatwidget", "jid", None, QtGui.QApplication.UnicodeUTF8))

