# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/widgets/chat/joingroupchat.ui'
#
# Created: Mon Apr 19 15:20:31 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_joingroupchat(object):
    def setupUi(self, joingroupchat):
        joingroupchat.setObjectName("joingroupchat")
        joingroupchat.resize(375, 380)
        self.gridlayout = QtGui.QGridLayout(joingroupchat)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label = QtGui.QLabel(joingroupchat)
        self.label.setMaximumSize(QtCore.QSize(48, 48))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/48x48/categories/conferences.png"))
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(joingroupchat)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(joingroupchat)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.vboxlayout1.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.vboxlayout1.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.vboxlayout1.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.vboxlayout1.addWidget(self.label_6)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.nickname = QtGui.QLineEdit(self.groupBox)
        self.nickname.setObjectName("nickname")
        self.vboxlayout2.addWidget(self.nickname)
        self.roomName = QtGui.QLineEdit(self.groupBox)
        self.roomName.setObjectName("roomName")
        self.vboxlayout2.addWidget(self.roomName)
        self.serverName = QtGui.QComboBox(self.groupBox)
        self.serverName.setEditable(True)
        self.serverName.setObjectName("serverName")
        self.vboxlayout2.addWidget(self.serverName)
        self.password = QtGui.QLineEdit(self.groupBox)
        self.password.setObjectName("password")
        self.vboxlayout2.addWidget(self.password)
        self.hboxlayout.addLayout(self.vboxlayout2)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.gridlayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(joingroupchat)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout1.setMargin(9)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.bookmarkNameLabel = QtGui.QLabel(self.groupBox_2)
        self.bookmarkNameLabel.setObjectName("bookmarkNameLabel")
        self.hboxlayout1.addWidget(self.bookmarkNameLabel)
        self.bookmarkName = QtGui.QLineEdit(self.groupBox_2)
        self.bookmarkName.setObjectName("bookmarkName")
        self.hboxlayout1.addWidget(self.bookmarkName)
        self.gridlayout1.addLayout(self.hboxlayout1, 1, 0, 1, 1)
        self.bookmarkChat = QtGui.QCheckBox(self.groupBox_2)
        self.bookmarkChat.setObjectName("bookmarkChat")
        self.gridlayout1.addWidget(self.bookmarkChat, 0, 0, 1, 1)
        self.autojoin = QtGui.QCheckBox(self.groupBox_2)
        self.autojoin.setObjectName("autojoin")
        self.gridlayout1.addWidget(self.autojoin, 2, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.buttons = QtGui.QGridLayout()
        self.buttons.setSpacing(6)
        self.buttons.setObjectName("buttons")
        self.browser = QtGui.QPushButton(joingroupchat)
        self.browser.setObjectName("browser")
        self.buttons.addWidget(self.browser, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(joingroupchat)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttons.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.gridlayout.addLayout(self.buttons, 4, 0, 1, 2)

        self.retranslateUi(joingroupchat)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), joingroupchat.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), joingroupchat.reject)
        QtCore.QObject.connect(self.bookmarkChat, QtCore.SIGNAL("toggled(bool)"), self.bookmarkName.setEnabled)
        QtCore.QObject.connect(self.bookmarkChat, QtCore.SIGNAL("toggled(bool)"), self.autojoin.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(joingroupchat)
        joingroupchat.setTabOrder(self.nickname, self.roomName)
        joingroupchat.setTabOrder(self.roomName, self.password)
        joingroupchat.setTabOrder(self.password, self.bookmarkChat)
        joingroupchat.setTabOrder(self.bookmarkChat, self.bookmarkName)
        joingroupchat.setTabOrder(self.bookmarkName, self.autojoin)

    def retranslateUi(self, joingroupchat):
        joingroupchat.setWindowTitle(QtGui.QApplication.translate("joingroupchat", "Join Chat Room", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("joingroupchat", "Chat rooms allow you to chat with more users in one window.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("joingroupchat", "Join the chat room", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("joingroupchat", "Your nickname:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("joingroupchat", "Room name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("joingroupchat", "Room server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("joingroupchat", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("joingroupchat", "Bookmark", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmarkNameLabel.setText(QtGui.QApplication.translate("joingroupchat", "Bookmark name:", None, QtGui.QApplication.UnicodeUTF8))
        self.bookmarkChat.setText(QtGui.QApplication.translate("joingroupchat", "Bookmark this chat room", None, QtGui.QApplication.UnicodeUTF8))
        self.autojoin.setText(QtGui.QApplication.translate("joingroupchat", "Join this chat room automaticaly at login", None, QtGui.QApplication.UnicodeUTF8))
        self.browser.setText(QtGui.QApplication.translate("joingroupchat", "Browse chat rooms", None, QtGui.QApplication.UnicodeUTF8))

